import {serialDilution,cellCount,linearRegression,bufferRecipe,cfu,doublingTime} from './bench-calc.js?v=2.0.0';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const f=n=>Number(n).toLocaleString('es-ES',{maximumFractionDigits:5});
const field=(label,id,value,type='number')=>`<label class="field">${label}<input id="b-${id}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(value)}"></label>`;
const tools=[['stocks','Stocks y seguridad'],['buffers','Buffers y medios'],['serial','Diluciones seriadas'],['cells','Cultivo celular'],['colony','Colonias e imágenes'],['plate','Mapa de placas'],['timers','Multicronómetro'],['calibration','Curva patrón'],['counter','Contadores'],['sequence','DNA y codones'],['inventory','Inventario'],['agenda','Agenda']];
let mode='stocks',context,tick,imageData=null,points=[],selectedWell='A1';
export function stopBenchTick(){clearInterval(tick);}
function b(){context.saved.bench??={};const x=context.saved.bench;for(const k of ['timers','inventory','agenda'])x[k]??=[];x.plate??={rows:8,cols:12,wells:{},name:'Placa 96'};x.counters??={};x.buffer??={name:'Mi buffer',volume:100,rows:[{name:'NaCl',type:'powder',final:8,stock:0}]};x.stockNotes??={};return x;}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const val=id=>$('#b-'+id)?.value, num=id=>Number(val(id));
const result=html=>{$('#b-result').innerHTML=html;};
const error=err=>result(`<p class="error">${esc(err.message)}</p>`);
const button=(id,label,primary=false)=>`<button id="b-${id}" class="button ${primary?'primary':''}">${label}</button>`;
const source=(url,label)=>{let safe='#';try{const parsed=new URL(url);if(['https:','http:'].includes(parsed.protocol))safe=parsed.href;}catch{}return `<a href="${esc(safe)}" rel="noopener noreferrer" target="_blank">${esc(label)}</a>`;};
export function reagentCard(c){return `<div class="reagent-card"><h3>Cómo disolver · ${esc(c.name)}</h3><p><strong>Disolvente inicial:</strong> ${esc(c.solvent||'No verificado para este producto')}</p><p><strong>Diluyente:</strong> ${esc(c.diluent||'Confirmar en la ficha del producto')}</p><p>${esc(c.preparation||'Añade una preparación validada para la forma química y concentración elegidas. La masa calculada no confirma solubilidad.')}</p>${c.product?`<p class="help">Referencia: ${esc(c.product)} · CAS ${esc(c.cas||'sin verificar')}</p>`:''}${c.preparationSource?source(c.preparationSource,'Fuente de preparación'):''}<h3>Seguridad del reactivo y del disolvente</h3><p>${esc(c.hazards||'Clasificación de peligro pendiente de revisión del producto exacto.')}</p><p>${esc(c.safety||'Revisa la SDS del producto y de cada disolvente: protección, incompatibilidades, almacenamiento, primeros auxilios y residuos.')}</p><p class="help">${esc(c.safetyStatus||'No se ha verificado la clasificación completa de seguridad. No equivale a ausencia de peligros.')}</p>${c.sds?source(c.sds,'Consultar producto / SDS'):source('https://www.sigmaaldrich.com/ES/es/documents-search?tab=sds','Buscar SDS por proveedor y referencia')}<p class="help">Fecha de consulta del catálogo: 01/10/2026. La SDS debe corresponder a tu producto, concentración y jurisdicción.</p></div>`;}
export function renderTools(ctx){context=ctx;const data=b();return `<div class="bench-shell"><aside class="panel bench-menu"><p class="eyebrow">BANCO DE TRABAJO</p>${tools.map(([id,label])=>`<button class="bench-tool ${mode===id?'active':''}" data-bench="${id}">${label}</button>`).join('')}<p class="help">Datos locales. Exportables desde el cuaderno. Inspirado en herramientas de laboratorio de uso común.</p></aside><section class="panel bench-main"><h2>${tools.find(t=>t[0]===mode)[1]}</h2>${views[mode](data)}</section></div>`;}
const views={
 stocks:()=>{const cs=context.compounds,c=cs.find(c=>c.id===context.compound)||cs[0];return `<p>Prepara un stock y calcula cuánto añadir al medio. El volumen de predisolvente forma parte del volumen final.</p><label class="field">Reactivo<select id="b-compound">${cs.map(x=>`<option value="${esc(x.id)}" ${x.id===c.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><div class="form-grid">${field('Stock (mg/mL)','stock',1)}${field('Volumen de stock (mL)','stock-volume',10)}${field('Pureza (%)','purity',100)}${field('Predisolvente usado (mL)','presolvent',0.1)}${field('Objetivo en medio (mg/L)','target',1)}${field('Volumen final de medio (mL)','medium-volume',1000)}</div>${button('calculate','Calcular receta',true)}<div id="b-result" aria-live="polite"></div>${reagentCard(c)}<label class="field">Mi preparación validada, pH y observaciones<textarea id="b-stock-note">${esc(b().stockNotes[c.id]||'')}</textarea></label>${button('save-stock','Guardar preparación personal')}`;},
 buffers:d=>`<p>Componentes en polvo (g/L) o stock y objetivo en la misma unidad. Ajuste de pH y aforo después de disolver.</p><div class="form-grid">${field('Nombre de la receta','buffer-name',d.buffer.name,'text')}${field('Volumen final (mL)','buffer-volume',d.buffer.volume)}</div><div class="table-scroll"><table><thead><tr><th>Componente</th><th>Formato</th><th>Final</th><th>Stock</th><th></th></tr></thead><tbody>${d.buffer.rows.map((r,i)=>`<tr data-buffer-row="${i}"><td><input aria-label="Nombre componente ${i+1}" data-r="name" value="${esc(r.name)}"></td><td><select data-r="type" aria-label="Formato componente ${i+1}"><option value="powder" ${r.type==='powder'?'selected':''}>Polvo g/L</option><option value="stock" ${r.type==='stock'?'selected':''}>Stock</option></select></td><td><input data-r="final" type="number" step="any" value="${r.final}" aria-label="Concentración final ${i+1}"></td><td><input data-r="stock" type="number" step="any" value="${r.stock}" aria-label="Concentración stock ${i+1}"></td><td><button class="icon-button" data-remove-row="${i}" aria-label="Eliminar componente ${i+1}">×</button></td></tr>`).join('')}</tbody></table></div><div class="button-row">${button('add-row','Añadir componente')}${button('calculate','Calcular y guardar',true)}</div><div id="b-result" aria-live="polite"></div><p class="help">El agua calculada es orientativa: los sólidos, el ajuste de pH y los suplementos afectan al volumen. Completa hasta el volumen final; confirma compatibilidad y esterilización para la formulación.</p>`,
 serial:()=>`<p>Concentración en una unidad común; transferencia y diluyente en µL.</p><div class="form-grid">${field('Concentración inicial','initial',100)}${field('Factor por paso (ej. 10)','factor',10)}${field('Transferencia por tubo (µL)','transfer',100)}${field('Número de pasos','steps',6)}</div>${button('calculate','Crear serie',true)}<div id="b-result" aria-live="polite"></div>`,
 cells:()=>`<p>Cámara Neubauer: cuadrados grandes de 1 mm², profundidad 0,1 mm. Cambia de método si tu cámara tiene otra geometría.</p><div class="form-grid">${field('Viables contadas','live',180)}${field('Muertas contadas','dead',20)}${field('Cuadrados grandes contados','squares',4)}${field('Factor de dilución total','dilution',2)}${field('Suspensión disponible (mL)','cell-volume',5)}${field('Células a sembrar por pozo','target-cells',100000)}${field('Población inicial','n0',100000)}${field('Población final','n1',400000)}${field('Tiempo de crecimiento (h)','hours',48)}</div>${button('calculate','Calcular cultivo',true)}<div id="b-result" aria-live="polite"></div>`,
 colony:()=>`<p>Conteo manual sobre imagen. Marca colonias o células con un toque; elimina la última marca para corregir. La imagen permanece en este dispositivo.</p><label class="field">Imagen de placa o microscopía<input id="b-image" type="file" accept="image/*"></label><label class="field">Clase de marca<select id="b-mark-class"><option>Colonia</option><option>Viable</option><option>Muerta</option><option>Eritrocito</option><option>Leucocito</option><option>Plaqueta</option><option>Otro</option></select></label><canvas id="b-canvas" width="800" height="600" aria-label="Imagen para conteo manual" tabindex="0"></canvas><div class="button-row">${button('undo','Deshacer marca')}${button('clear-marks','Limpiar marcas')}${button('export-image','Exportar imagen anotada')}${button('export-count','Exportar conteo CSV')}</div><div class="form-grid">${field('Volumen sembrado (mL)','plated',0.1)}${field('Fracción de dilución (ej. 0.0001)','dilution-fraction',0.0001)}${field('Distancia de calibración (µm)','distance',100)}</div><p class="help">Para medir: activa medición y marca dos extremos de la escala, después dos extremos del objeto. No es un contador automático ni una interpretación clínica.</p><label class="checkbox-field"><input type="checkbox" id="b-measure">Modo medición (4 puntos)</label><div id="b-result" aria-live="polite"></div>`,
 plate:d=>`<p>Etiqueta pozos, asigna grupos y exporta la placa para tu PCR o ensayo. Los cambios se guardan automáticamente.</p><div class="form-grid">${field('Nombre de placa','plate-name',d.plate.name,'text')}<label class="field">Formato<select id="b-plate-size">${[[2,3],[3,4],[4,6],[8,12],[16,24]].map(([r,c])=>`<option value="${r},${c}" ${d.plate.rows===r&&d.plate.cols===c?'selected':''}>${r*c} pozos</option>`).join('')}</select></label></div><div class="plate-scroll"><div class="well-grid" style="--cols:${d.plate.cols}">${Array.from({length:d.plate.rows*d.plate.cols},(_,i)=>{const id=String.fromCharCode(65+Math.floor(i/d.plate.cols))+(i%d.plate.cols+1),w=d.plate.wells[id]||{};return `<button class="well ${selectedWell===id?'selected':''}" data-well="${id}" style="background:${/^#[0-9a-f]{6}$/i.test(w.color)?w.color:'#eaf1ff'}"><strong>${id}</strong><span>${esc(w.label||'—')}</span></button>`;}).join('')}</div></div><h3>Pozo <span id="b-well-id">${selectedWell}</span></h3><div class="form-grid">${field('Muestra / control','well-label',d.plate.wells[selectedWell]?.label||'','text')}${field('Grupo / condición','well-group',d.plate.wells[selectedWell]?.group||'','text')}${field('Color','well-color',d.plate.wells[selectedWell]?.color||'#dbeafe','color')}</div><div class="button-row">${button('save-well','Guardar pozo',true)}${button('fill-row','Aplicar a fila')}${button('export-plate','Exportar CSV')}${button('print-plate','Imprimir placa')}</div><p class="help">Cambiar formato conserva etiquetas de pozos compartidos. Verifica los pozos ocultos antes de volver a otro formato.</p>`,
 timers:d=>`<p>Cronómetros independientes con nombre. Se conservan por hora de vencimiento al navegar o recargar; la actualización y el aviso requieren abrir la app.</p><div class="form-grid">${field('Nombre','timer-name','Incubación','text')}${field('Minutos','timer-min',5)}</div>${button('add-timer','Crear cronómetro',true)}<div class="timer-grid">${d.timers.map(t=>`<article class="timer-card"><h3>${esc(t.name)}</h3><strong data-timer-display="${esc(t.id)}"></strong><div class="button-row"><button class="button small" data-toggle-timer="${esc(t.id)}">${t.deadline?'Pausa':'Iniciar'}</button><button class="button small" data-reset-timer="${esc(t.id)}">Reiniciar</button><button class="icon-button" data-delete-timer="${esc(t.id)}" aria-label="Eliminar ${esc(t.name)}">×</button></div></article>`).join('')}</div><p class="help">El navegador puede suspender la app en segundo plano. Usa el temporizador del equipo para pasos críticos.</p>`,
 calibration:()=>`<p>Regresión lineal de curva patrón: una pareja concentración,señal por línea, con punto decimal. No transforma ni fuerza paso por cero.</p><label class="field">Pares x,y<textarea id="b-pairs">0,0.02\n1,0.12\n2,0.22\n4,0.42\n8,0.82</textarea></label><div class="form-grid">${field('Señal de muestra','signal',0.27)}${field('Factor de dilución de muestra','sample-factor',1)}</div>${button('calculate','Ajustar curva',true)}<div id="b-result" aria-live="polite"></div>`,
 counter:d=>`<p>Contadores por clase para recuentos manuales y diferenciales. Exporta valores absolutos y porcentajes.</p><div class="button-row">${field('Nueva clase','counter-name','Neutrófilos','text')}${button('add-counter','Añadir clase')}</div><div class="counter-grid">${Object.entries(d.counters).map(([name,n],i)=>`<div class="timer-card"><h3>${esc(name)}</h3><strong>${n}</strong><div class="button-row"><button class="button" data-count="${i}" data-delta="-1">−1</button><button class="button primary" data-count="${i}" data-delta="1">+1</button></div></div>`).join('')}</div><div class="button-row">${button('export-counters','Exportar CSV')}${button('reset-counters','Poner a cero')}</div><p class="help">Uso de investigación. Los porcentajes describen las clases contadas, no un diagnóstico.</p>`,
 sequence:()=>`<p>Herramientas locales para DNA: complementaria inversa, GC, traducción del código estándar y Tm aproximada de oligos cortos.</p><label class="field">DNA 5′ → 3′ (A,C,G,T; admite FASTA)<textarea id="b-dna">ATGGCTTTCGAGTAA</textarea></label><label class="field">Marco de lectura<select id="b-frame"><option value="0">+1</option><option value="1">+2</option><option value="2">+3</option></select></label>${button('calculate','Analizar secuencia',true)}<div id="b-result" aria-live="polite"></div><div class="form-grid">${field('A260 corregida','a260',0.2)}${field('Factor de dilución','dna-dilution',10)}<label class="field">Tipo<select id="b-nucleic-type"><option value="50">DNA doble hebra · 50 µg/mL</option><option value="40">RNA · 40 µg/mL</option><option value="33">DNA hebra simple · 33 µg/mL</option></select></label></div>${button('absorbance','Calcular concentración por absorbancia')}<div id="b-abs-result"></div><p class="help">A260 normalizada a 1 cm, blanco sustraído. Factores generales; no comprueban pureza ni integridad.</p>`,
 inventory:d=>`<p>Control local de lotes, caducidad, ubicación y documentación. No sincronizado entre dispositivos.</p><div class="form-grid">${field('Reactivo','item-name','','text')}${field('Lote','lot','','text')}${field('Cantidad y unidad','amount','','text')}${field('Ubicación','location','','text')}${field('Caducidad','expiry','','date')}${field('URL de SDS / ficha','sds','','url')}</div>${button('add-item','Añadir lote',true)}<div class="table-scroll"><table><thead><tr><th>Reactivo / lote</th><th>Stock</th><th>Ubicación</th><th>Caducidad</th><th>Ficha</th><th></th></tr></thead><tbody>${d.inventory.map(t=>`<tr><td>${esc(t.name)}<br>${esc(t.lot)}</td><td>${esc(t.amount)}</td><td>${esc(t.location)}</td><td>${esc(t.expiry)}${t.expiry&&t.expiry<new Date().toISOString().slice(0,10)?' · Revisar caducidad':''}</td><td>${/^https?:\/\//.test(t.sds)?source(t.sds,'SDS / ficha'):'Pendiente'}</td><td><button class="icon-button" data-remove-item="${esc(t.id)}" aria-label="Eliminar lote">×</button></td></tr>`).join('')}</tbody></table></div>${button('export-inventory','Exportar inventario CSV')}`,
 agenda:d=>`<p>Planifica ensayos y revisiones. Las tareas quedan guardadas en este navegador; exporta un archivo de calendario para obtener recordatorios en tu móvil.</p><div class="form-grid">${field('Experimento / tarea','task','','text')}${field('Fecha y hora','date','','datetime-local')}${field('Notas','task-note','','text')}</div>${button('add-task','Guardar tarea',true)}<div>${[...d.agenda].sort((a,b)=>a.date.localeCompare(b.date)).map(t=>`<div class="agenda-row"><label class="checkbox-field"><input type="checkbox" data-complete-task="${esc(t.id)}" ${t.done?'checked':''}><strong>${esc(t.name)}</strong></label><p>${esc(t.date.replace('T',' '))} · ${esc(t.note)}</p><button class="button small" data-ics="${esc(t.id)}">Exportar calendario</button><button class="icon-button" data-remove-task="${esc(t.id)}" aria-label="Eliminar tarea">×</button></div>`).join('')}</div>`
};
function redraw(){context.persist();context.render();}
function csv(name,rows){context.download(name,'\uFEFF'+rows.map(row=>row.map(v=>{let s=String(v??'');if(/^[=+@-]/.test(s)&&typeof v!=='number')s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
function bufferInputs(){return $$('[data-buffer-row]').map(row=>Object.fromEntries([...row.querySelectorAll('[data-r]')].map(el=>[el.dataset.r,['final','stock'].includes(el.dataset.r)?Number(el.value):el.value])));}
export function bindTools(ctx){context=ctx;b();$$('[data-bench]').forEach(el=>el.onclick=()=>{mode=el.dataset.bench;context.render();});
 if(mode==='stocks'){$('#b-compound').onchange=()=>{context.setCompound(val('compound'));context.render();};$('#b-save-stock').onclick=()=>{b().stockNotes[val('compound')]=$('#b-stock-note').value;context.persist();context.toast('Preparación personal guardada.');};}
 if($('#b-calculate'))$('#b-calculate').onclick=calculate;
 if(mode==='buffers'){$('#b-add-row').onclick=()=>{b().buffer.rows=bufferInputs();b().buffer.name=val('buffer-name');b().buffer.volume=num('buffer-volume');b().buffer.rows.push({name:'Componente',type:'stock',final:1,stock:10});redraw();};$$('[data-remove-row]').forEach(el=>el.onclick=()=>{b().buffer.rows=bufferInputs();b().buffer.rows.splice(Number(el.dataset.removeRow),1);redraw();});}
 if(mode==='timers')bindTimers();
 if(mode==='plate')bindPlate();
 if(mode==='colony')bindImage();
 if(mode==='counter')bindCounters();
 if(mode==='inventory')bindInventory();
 if(mode==='agenda')bindAgenda();
 if(mode==='sequence')$('#b-absorbance').onclick=()=>{try{const a=num('a260'),d=num('dna-dilution');if(!Number.isFinite(a)||a<0||!Number.isFinite(d)||d<=0)throw Error('Absorbancia ≥ 0 y dilución > 0.');$('#b-abs-result').innerHTML=`<div class="result"><strong>${f(a*d*num('nucleic-type'))} ng/µL</strong></div>`;}catch(err){$('#b-abs-result').textContent=err.message;}};
}
function calculate(){try{
 if(mode==='stocks'){const c=context.compounds.find(c=>c.id===val('compound')),stock=num('stock'),volume=num('stock-volume'),p=num('purity'),pre=num('presolvent'),target=num('target'),medium=num('medium-volume');if([stock,volume,p,medium].some(x=>!Number.isFinite(x)||x<=0)||p>100||!Number.isFinite(pre)||pre<0||pre>=volume||!Number.isFinite(target)||target<0)throw Error('Comprueba concentración, pureza, volúmenes y predisolvente.');const mass=stock*volume/(p/100),add=target*medium/(stock*1000);if(add>medium)throw Error('El stock es menos concentrado que el medio objetivo.');result(`<div class="result"><strong>${f(mass)} mg de ${esc(c.name)}</strong><p>Predisolver según ficha en ${f(pre)} mL (cantidad introducida por ti, no validada automáticamente). Completar hasta ${f(volume)} mL; diluyente orientativo ${f(volume-pre)} mL. Disolvente: ${esc(c.solvent||'pendiente de verificar')}.</p><p>Añadir ${f(add*1000)} µL de stock al medio y completar a ${f(medium)} mL finales → ${f(target)} mg/L.</p><p>Predisolvente aportado: ${f(pre/volume*add)} mL · ${f(pre/volume*add/medium*100)} % v/v final. Confirmar tolerancia, pH y esterilidad.</p></div>`);}
 if(mode==='buffers'){const r=bufferRecipe(bufferInputs(),num('buffer-volume'));b().buffer={name:val('buffer-name'),volume:r.volume,rows:bufferInputs()};context.persist();result(`<div class="result"><h3>${esc(b().buffer.name)}</h3>${r.rows.map(x=>`<p>${esc(x.name)}: ${f(x.quantity)} ${x.unit}</p>`).join('')}<p>Diluyente orientativo: ${f(r.water)} mL. Disolver, ajustar pH y completar a ${f(r.volume)} mL finales.</p></div>`);}
 if(mode==='serial'){const rows=serialDilution(num('initial'),num('factor'),num('transfer'),num('steps'));result(`<div class="table-scroll"><table><thead><tr><th>Tubo</th><th>Concentración</th><th>Transferencia µL</th><th>Diluyente µL</th><th>Resto µL</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.step}</td><td>${f(r.concentration)}</td><td>${f(r.transfer)}</td><td>${f(r.diluent)}</td><td>${f(r.remaining)}</td></tr>`).join('')}</tbody></table></div><p class="help">Mezclar cada tubo antes de transferir; usar puntas nuevas. El resto descuenta la transferencia siguiente, salvo en el último tubo.</p>`);}
 if(mode==='cells'){const c=cellCount(num('live'),num('dead'),num('squares'),num('dilution'),num('cell-volume'),num('target-cells'));const dt=doublingTime(num('n0'),num('n1'),num('hours'));result(`<div class="result"><strong>${f(c.viable)} células viables/mL</strong><p>Viabilidad: ${f(c.viability)} % · Total: ${f(c.total)} células/mL<br>Disponibles: ${f(c.available)} viables<br>Sembrar: ${c.viable?f(c.seedMl*1000)+' µL':'No hay células viables'} por pozo${c.seedMl>num('cell-volume')?' · Cantidad disponible insuficiente':''}<br>Duplicación: ${f(dt)} h (crecimiento exponencial asumido).</p></div>`);}
 if(mode==='calibration'){const pts=$('#b-pairs').value.trim().split(/\n/).filter(Boolean).map(l=>l.trim().split(/[,;\t ]+/).map(Number)),r=linearRegression(pts),signal=num('signal'),factor=num('sample-factor');if(!Number.isFinite(signal)||!Number.isFinite(factor)||factor<=0||Math.abs(r.slope)<1e-12)throw Error('Señal finita, dilución positiva y pendiente distinta de cero.');const raw=(signal-r.intercept)/r.slope,x=raw*factor;result(`<div class="result"><strong>${f(x)} unidades de concentración</strong><p>y = ${f(r.slope)} x + ${f(r.intercept)} · R² ${f(r.r2)} · n ${r.n}<br>Antes de corregir dilución: ${f(raw)}${raw<r.min||raw>r.max?' · Fuera de la curva: extrapolación':''}</p></div>${curve(pts,r)}`);}
 if(mode==='sequence'){const seq=$('#b-dna').value.replace(/^>.*$/gm,'').replace(/\s/g,'').toUpperCase();if(!seq||seq.length>100000||/[^ACGT]/.test(seq))throw Error('Introduce hasta 100000 bases A,C,G,T sin ambigüedad.');const gc=(seq.match(/[GC]/g)||[]).length,rc=[...seq].reverse().map(c=>({A:'T',T:'A',G:'C',C:'G'}[c])).join('');let protein='';const bases='TCAG',aa='FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG';for(let i=num('frame');i+2<seq.length;i+=3){const cod=seq.slice(i,i+3);protein+=aa[bases.indexOf(cod[0])*16+bases.indexOf(cod[1])*4+bases.indexOf(cod[2])];}result(`<div class="result"><p>${seq.length} nt · GC ${f(gc/seq.length*100)} %${seq.length<=20?` · Tm Wallace orientativa ${2*(seq.length-gc)+4*gc} °C`:''}</p><h3>Complementaria inversa 5′ → 3′</h3><p class="sequence-output">${esc(rc)}</p><h3>Traducción estándar</h3><p class="sequence-output">${esc(protein)}${(seq.length-num('frame'))%3?' · Codón final incompleto':''}</p><p class="help">* = stop. Tm corta orientativa, sin sales ni condiciones de polimerasa. No determina primers válidos.</p></div>`);}
 }catch(err){error(err);}}
function curve(pts,r){const xmin=r.min,xmax=r.max,ymin=Math.min(...pts.map(p=>p[1])),ymax=Math.max(...pts.map(p=>p[1])),x=v=>40+(v-xmin)/(xmax-xmin)*540,y=v=>210-(v-ymin)/(ymax-ymin||1)*180;return `<svg viewBox="0 0 620 250" class="thermal-chart" role="img" aria-label="Curva de calibración lineal"><path d="M40 20V210H590" fill="none" stroke="#8496ad"/><path d="M${x(xmin)} ${y(r.slope*xmin+r.intercept)}L${x(xmax)} ${y(r.slope*xmax+r.intercept)}" stroke="#5681f7" stroke-width="2"/>${pts.map(p=>`<circle cx="${x(p[0])}" cy="${y(p[1])}" r="4" fill="#7984e9"/>`).join('')}<text x="40" y="240">${f(xmin)}</text><text x="530" y="240">${f(xmax)}</text></svg>`;}
function bindTimers(){const d=b();$('#b-add-timer').onclick=()=>{const seconds=num('timer-min')*60;if(!val('timer-name').trim()||!Number.isFinite(seconds)||seconds<=0||seconds>604800){context.toast('Nombre y tiempo entre 0 y 10080 minutos.');return;}d.timers.push({id:crypto.randomUUID(),name:val('timer-name'),duration:seconds,remaining:seconds,deadline:null});redraw();};$$('[data-toggle-timer]').forEach(el=>el.onclick=()=>{const t=d.timers.find(t=>t.id===el.dataset.toggleTimer);if(t.deadline){t.remaining=Math.max(0,(t.deadline-Date.now())/1000);t.deadline=null;}else if(t.remaining>0)t.deadline=Date.now()+t.remaining*1000;redraw();});$$('[data-reset-timer]').forEach(el=>el.onclick=()=>{const t=d.timers.find(t=>t.id===el.dataset.resetTimer);t.deadline=null;t.remaining=t.duration;redraw();});$$('[data-delete-timer]').forEach(el=>el.onclick=()=>{d.timers=d.timers.filter(t=>t.id!==el.dataset.deleteTimer);redraw();});const update=()=>{$$('[data-timer-display]').forEach(el=>{const t=d.timers.find(t=>t.id===el.dataset.timerDisplay),s=Math.max(0,Math.ceil(t.deadline?(t.deadline-Date.now())/1000:t.remaining));el.textContent=s===0?'Tiempo cumplido':String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');el.classList.toggle('expired',s===0);if(t.deadline&&s===0){t.deadline=null;t.remaining=0;context.persist();context.toast(t.name+': tiempo cumplido.');}});};update();tick=setInterval(update,500);}
function bindPlate(){const p=b().plate;$('#b-plate-size').onchange=()=>{const [rows,cols]=val('plate-size').split(',').map(Number);p.rows=rows;p.cols=cols;selectedWell='A1';redraw();};$('#b-plate-name').onchange=()=>{p.name=val('plate-name');context.persist();};$$('[data-well]').forEach(el=>el.onclick=()=>{selectedWell=el.dataset.well;context.render();});const get=()=>({label:val('well-label'),group:val('well-group'),color:val('well-color')});$('#b-save-well').onclick=()=>{p.wells[selectedWell]=get();redraw();};$('#b-fill-row').onclick=()=>{for(let col=1;col<=p.cols;col++)p.wells[selectedWell[0]+col]=get();redraw();};$('#b-export-plate').onclick=()=>csv('molab-placa.csv',[['Placa','Pozo','Muestra','Grupo','Color'],...Array.from({length:p.rows*p.cols},(_,i)=>{const id=String.fromCharCode(65+Math.floor(i/p.cols))+(i%p.cols+1),w=p.wells[id]||{};return [p.name,id,w.label,w.group,w.color];})]);$('#b-print-plate').onclick=()=>window.print();}
function paint(){const canvas=$('#b-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);if(imageData)ctx.drawImage(imageData,0,0,canvas.width,canvas.height);else{ctx.fillStyle='#eef3fa';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#52627b';ctx.font='20px sans-serif';ctx.fillText('Carga una imagen para empezar',30,60);}for(const [i,p] of points.entries()){ctx.beginPath();ctx.strokeStyle=p.kind==='Medición'?'#06b6d4':'#f43f5e';ctx.lineWidth=3;ctx.arc(p.x,p.y,8,0,2*Math.PI);ctx.stroke();ctx.fillStyle='#ffffff';ctx.font='bold 14px sans-serif';ctx.fillText(i+1,p.x+10,p.y-10);}if(points.length&&$('#b-result')){const counts=points.filter(p=>p.kind!=='Medición').reduce((a,p)=>(a[p.kind]=(a[p.kind]||0)+1,a),{});let extra='';try{const colonies=counts.Colonia||0;extra=`<p>${colonies} colonias · ${f(cfu(colonies,num('plated'),num('dilution-fraction')))} UFC/mL (conteo manual; confirma rango contable y dilución).</p>`;const m=points.filter(p=>p.kind==='Medición');if(m.length>=4){const distance=Math.hypot(m[1].x-m[0].x,m[1].y-m[0].y);if(distance>0&&num('distance')>0)extra+=`<p>Longitud: ${f(Math.hypot(m[3].x-m[2].x,m[3].y-m[2].y)/distance*num('distance'))} µm</p>`;}}catch(err){extra=`<p>${esc(err.message)}</p>`;}result(`<div class="result">${Object.entries(counts).map(([k,n])=>`<p>${esc(k)}: ${n}</p>`).join('')}${extra}</div>`);}else if($('#b-result'))result('<p class="help">Sin marcas todavía.</p>');}
function bindImage(){paint();$('#b-image').onchange=ev=>{const file=ev.target.files[0];if(!file)return;if(file.size>20000000){context.toast('Imagen máxima 20 MB.');return;}const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{imageData=img;const canvas=$('#b-canvas');if(canvas){canvas.width=Math.min(1600,img.naturalWidth);canvas.height=Math.round(canvas.width*img.naturalHeight/img.naturalWidth);points=[];paint();}URL.revokeObjectURL(url);};img.onerror=()=>{URL.revokeObjectURL(url);context.toast('No se pudo leer la imagen.');};img.src=url;};$('#b-canvas').onclick=ev=>{if(!imageData)return;const rect=ev.currentTarget.getBoundingClientRect();points.push({x:(ev.clientX-rect.left)/rect.width*ev.currentTarget.width,y:(ev.clientY-rect.top)/rect.height*ev.currentTarget.height,kind:$('#b-measure').checked?'Medición':val('mark-class')});paint();};$('#b-undo').onclick=()=>{points.pop();paint();};$('#b-clear-marks').onclick=()=>{points=[];paint();};$('#b-export-image').onclick=()=>{const a=document.createElement('a');a.href=$('#b-canvas').toDataURL('image/png');a.download='molab-conteo.png';a.click();};$('#b-export-count').onclick=()=>csv('molab-conteo.csv',[['Marca','Clase','X píxeles','Y píxeles'],...points.map((p,i)=>[i+1,p.kind,p.x,p.y])]);$$('#b-plated,#b-dilution-fraction,#b-distance').forEach(el=>el.oninput=paint);}
function bindCounters(){const d=b();$('#b-add-counter').onclick=()=>{const name=val('counter-name').trim();if(!name)return;d.counters[name]??=0;redraw();};$$('[data-count]').forEach(el=>el.onclick=()=>{const name=Object.keys(d.counters)[Number(el.dataset.count)];d.counters[name]=Math.max(0,d.counters[name]+Number(el.dataset.delta));redraw();});$('#b-reset-counters').onclick=()=>{for(const k of Object.keys(d.counters))d.counters[k]=0;redraw();};$('#b-export-counters').onclick=()=>{const sum=Object.values(d.counters).reduce((s,n)=>s+n,0);csv('molab-contadores.csv',[['Clase','Conteo','Porcentaje'],...Object.entries(d.counters).map(([k,n])=>[k,n,sum?n/sum*100:0])]);};}
function bindInventory(){const d=b();$('#b-add-item').onclick=()=>{if(!val('item-name').trim())return;const sds=val('sds');if(sds&&!/^https?:\/\//.test(sds)){context.toast('La ficha requiere URL http o https.');return;}d.inventory.push({id:crypto.randomUUID(),name:val('item-name'),lot:val('lot'),amount:val('amount'),location:val('location'),expiry:val('expiry'),sds});redraw();};$$('[data-remove-item]').forEach(el=>el.onclick=()=>{d.inventory=d.inventory.filter(t=>t.id!==el.dataset.removeItem);redraw();});$('#b-export-inventory').onclick=()=>csv('molab-inventario.csv',[['Reactivo','Lote','Cantidad','Ubicación','Caducidad','SDS'],...d.inventory.map(t=>[t.name,t.lot,t.amount,t.location,t.expiry,t.sds])]);}
function bindAgenda(){const d=b();$('#b-add-task').onclick=()=>{if(!val('task').trim()||!val('date')){context.toast('Indica tarea y fecha.');return;}d.agenda.push({id:crypto.randomUUID(),name:val('task'),date:val('date'),note:val('task-note'),done:false});redraw();};$$('[data-complete-task]').forEach(el=>el.onchange=()=>{d.agenda.find(t=>t.id===el.dataset.completeTask).done=el.checked;context.persist();});$$('[data-remove-task]').forEach(el=>el.onclick=()=>{d.agenda=d.agenda.filter(t=>t.id!==el.dataset.removeTask);redraw();});$$('[data-ics]').forEach(el=>el.onclick=()=>{const t=d.agenda.find(t=>t.id===el.dataset.ics),dt=new Date(t.date),icsEscape=s=>s.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;'),date=dt.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');context.download('molab-tarea.ics',['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Molab//Agenda//ES','BEGIN:VEVENT','UID:'+t.id+'@molab.local','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),'DTSTART:'+date,'SUMMARY:'+icsEscape(t.name),'DESCRIPTION:'+icsEscape(t.note),'END:VEVENT','END:VCALENDAR'].join('\r\n'),'text/calendar');});}
