export const checked='2026-10-01';
export const sources=[
 {id:'neb',name:'New England Biolabs',short:'NEB',color:'#1760c2',url:'https://www.neb.com/en-us/tools-and-resources/protocols'},
 {id:'thermo',name:'Thermo Fisher Scientific',short:'TF',color:'#d64748',url:'https://www.thermofisher.com/us/en/home/references/protocols.html'},
 {id:'biorad',name:'Bio-Rad',short:'BR',color:'#368477',url:'https://www.bio-rad.com/sites/default/files/2021-11/Bulletin_7431.pdf'},
 {id:'promega',name:'Promega',short:'P',color:'#305d9b',url:'https://www.promega.com/resources/protocols/'},
 {id:'qiagen',name:'QIAGEN',short:'Q',color:'#407bbe',url:'https://www.qiagen.com/us/resources'},
 {id:'sigma',name:'Merck · Sigma-Aldrich',short:'M',color:'#9854b6',url:'https://www.sigmaaldrich.com/'},
 {id:'zymo',name:'Zymo Research',short:'Z',color:'#db8d27',url:'https://www.zymoresearch.com/products/quick-dna-miniprep'},
 {id:'mn',name:'MACHEREY-NAGEL',short:'MN',color:'#da655d',url:'https://www.mn-net.com/media/pdf/45/51/02/Instruction-NucleoSpin-Plasmid.pdf'},
 {id:'agilent',name:'Agilent',short:'A',color:'#078786',url:'https://www.agilent.com/en/product/mutagenesis-cloning/mutagenesis-kits/site-directed-mutagenesis-kits/quikchange-233116'},
 {id:'takara',name:'Takara Bio',short:'T',color:'#497ece',url:'https://help.takarabio.com/36168/kb/category/110155/in-fusion'},
 {id:'himedia',name:'HiMedia',short:'HM',color:'#44895d',url:'https://www.himedialabs.com/media/TD/M063A.pdf'},
 {id:'atcc',name:'ATCC',short:'AT',color:'#744799',url:'https://www.atcc.org/resources/culture-guides/animal-cell-culture-guide'}
];
const s=(title,text,seconds=0,conditions='')=>({title,text,seconds:Number(seconds),conditions});
const q5pdf='https://intl.neb.com/-/media/nebus/files/manuals/manuale0555.pdf?rev=aa908f8055e84c098ef15ac6fc1c7377';
const dream='https://documents.thermofisher.com/TFS-Assets/LSG/manuals/MAN0012702_DreamTaq_K1071_UG.pdf';
const hifi='https://www.neb.com/en/-/media/nebus/files/manuals/manuale2621_e5520.pdf';
const gotaq='https://worldwide.promega.com/-/media/files/resources/protocols/technical-manuals/101/gotaq-qpcr-master-mix-protocol.pdf?rev=ab3c8f7ad767498ebd46346ce8e36cac';
const wb='https://www.bio-rad.com/sites/default/files/2021-11/Bulletin_7431.pdf';
const zymo='https://files.zymoresearch.com/quick-protocol/_d4068_d4069_quick-dna_miniprep_plus_quick_protocol.pdf';
export const protocols=[
 {id:'q5',manufacturer:'neb',category:'PCR',title:'Q5® High-Fidelity PCR',subtitle:'Amplificación de alta fidelidad · Master Mix 2X',tags:['PCR','Cloning','DNA'],status:'reviewed',source:q5pdf,sourceType:'PDF',version:'E0555 · v5.0 · 07/2025',pages:'3–5',duration:'~35 min',
 description:'Amplificación de DNA con una polimerasa correctora. El formato 2X reúne enzima, nucleótidos y buffer; añade primers y molde.',mechanism:'Los ciclos separan las hebras, hibridan primers y extienden DNA. La actividad exonucleasa 3′→5′ mejora la fidelidad.',
 volume:25,components:[{name:'Q5 Master Mix 2X',volume:12.5},{name:'Primer forward · 10 µM',volume:1.25},{name:'Primer reverse · 10 µM',volume:1.25},{name:'DNA molde',volume:1,template:true}],cycles:30,
 thermal:[{label:'Desnaturalización inicial',temp:98,seconds:30},{label:'Desnaturalización',temp:98,seconds:10,repeat:true},{label:'Hibridación',temp:65,seconds:20,repeat:true},{label:'Extensión',temp:72,seconds:30,repeat:true},{label:'Extensión final',temp:72,seconds:120},{label:'Conservación',temp:4,seconds:0}],
 assumptions:'65 °C de hibridación, 1 µL de molde y 30 s de extensión son valores iniciales editables; ajusta con Tm, concentración y longitud. Manual: 25–35 ciclos, 50–72 °C, 20–30 s/kb.',
 steps:[s('Preparar en hielo','Mezcla reactivos; utiliza los volúmenes calculados.','0','Hielo'),s('Distribuir y añadir molde','Dispensa la mezcla común; añade DNA por tubo y agua al NTC.'),s('Mezclar','Mezcla suavemente y centrifuga brevemente.'),s('Termociclado','Carga los tubos y programa las fases configuradas.',0,'Programa editable'),s('Finalizar','Recupera y registra el resultado.')],
 tips:[{text:'Calcula la hibridación con la herramienta específica de Q5.',url:'https://tmcalculator.neb.com/',label:'NEB Tm Calculator'},{text:'El manual incluye diagnóstico de bandas inespecíficas y ausencia de producto.',url:q5pdf,label:'Manual · p. 5'}]},
 {id:'dreamtaq',manufacturer:'thermo',category:'PCR',title:'DreamTaq™ PCR Master Mix',subtitle:'PCR de rutina · Formato 2X',tags:['PCR','DNA','Genotipado'],status:'reviewed',source:dream,sourceType:'PDF',version:'MAN0012702 · Rev. B.00 · 2016',pages:'1–2',duration:'~50 min',
 description:'Mezcla lista para PCR rutinaria. Incluye polimerasa Taq, buffer, MgCl₂ y dNTPs.',mechanism:'Amplifica por ciclos de separación, hibridación y extensión. Requiere primers y DNA; ajusta cada ensayo.',volume:50,components:[{name:'DreamTaq Master Mix 2X',volume:25},{name:'Primer forward · 10 µM',volume:2.5},{name:'Primer reverse · 10 µM',volume:2.5},{name:'DNA molde',volume:1,template:true}],cycles:30,
 thermal:[{label:'Desnaturalización inicial',temp:95,seconds:120},{label:'Desnaturalización',temp:95,seconds:30,repeat:true},{label:'Hibridación',temp:55,seconds:30,repeat:true},{label:'Extensión',temp:72,seconds:60,repeat:true},{label:'Extensión final',temp:72,seconds:600}],assumptions:'55 °C y 1 µL de molde son ejemplos editables. Hibridación: Tm−5 °C. Extensión: 1 min hasta 2 kb; para productos mayores ajusta según el manual. Primers: 0,1–1 µM.',
 steps:[s('Descongelar y mezclar','Mezcla el 2X y centrifuga brevemente.'),s('Montar en hielo','Prepara mezcla común; distribuye y añade molde.','0','Hielo'),s('Cerrar tubos','Mezcla y centrifuga. Sin tapa caliente, consulta la capa de aceite mineral indicada en el manual.'),s('Termociclado','Introduce el programa revisado.',0,'Programa editable'),s('Registrar','Guarda las observaciones.')],tips:[{text:'Incluye un control sin molde para detectar contaminación.',url:dream,label:'Manual · p. 1'}]},
 {id:'gotaq',manufacturer:'promega',category:'qPCR',title:'GoTaq® qPCR Master Mix',subtitle:'Detección con BRYT Green · Ciclos estándar',tags:['qPCR','Expresión','DNA'],status:'reviewed',source:gotaq,sourceType:'PDF',version:'TM318 · 10/2024',pages:'5–7',duration:'~52 min',
 description:'Mezcla hot-start para cuantificar DNA con fluorescencia. No contiene transcriptasa inversa.',mechanism:'BRYT Green detecta DNA de doble hebra durante la amplificación. Una curva de fusión ayuda a evaluar especificidad.',volume:20,components:[{name:'GoTaq qPCR Master Mix 2X',volume:10},{name:'Primer forward · stock 20X',volume:1},{name:'Primer reverse · stock 20X',volume:1},{name:'DNA molde',volume:1,template:true}],cycles:40,
 thermal:[{label:'Activación',temp:95,seconds:120},{label:'Desnaturalización',temp:95,seconds:15,repeat:true},{label:'Hibridación + extensión',temp:60,seconds:60,repeat:true}],assumptions:'El molde de 1 µL es editable. Primers: optimizar 200 nM–1 µM; stocks 20X. Según instrumento, añadir 0,2 µL de CXR y descontarlo del agua. Adquisición y curva de fusión se programan en el equipo.',
 steps:[s('Preparar reactivos','Descongela sin sobrepasar temperatura ambiente y mezcla suavemente.'),s('Comprobar CXR','Consulta la compatibilidad del equipo; ajusta el reactivo opcional.'),s('Distribuir la mezcla','Añade molde por pocillo; usa agua para NTC.'),s('Sellar y centrifugar','Protege de luz prolongada.'),s('Termociclado','Configura fluorescencia y curva de fusión en el instrumento.',0,'Programa editable'),s('Registrar','Guarda resultados y controles.')],tips:[{text:'Documenta controles, eficiencia y especificidad.',url:'https://doi.org/10.1373/clinchem.2008.112797',label:'MIQE · Bustin et al., 2009',kind:'Paper'}]},
 {id:'hifi',manufacturer:'neb',category:'Cloning',title:'NEBuilder® HiFi DNA Assembly',subtitle:'Ensamblaje de fragmentos con solapamientos',tags:['Cloning','DNA','Assembly'],status:'reviewed',source:hifi,sourceType:'PDF',version:'E2621 / E5520',pages:'8',duration:'15–60 min',description:'Ensamblaje isotérmico de fragmentos de DNA con extremos homólogos.',mechanism:'La mezcla coordina el procesamiento y la unión de regiones solapantes para generar el constructo.',volume:20,components:[{name:'NEBuilder HiFi Master Mix 2X',volume:10},{name:'DNA vector + insertos',volume:2,template:true}],assumptions:'2 µL de DNA es un ejemplo. Calcula cantidades molares. Para 2–3 fragmentos: vector:inserto 1:2; 4–6: 1:1. Ajusta tiempo entre 15 y 60 min según número de fragmentos.',
 steps:[s('Diseño','Verifica homología, orientación y calidad de fragmentos.'),s('Montaje en hielo','Combina DNA, 2X y agua hasta 20 µL.',0,'Hielo'),s('Ensamblaje','Incuba 15 min para 2–3 fragmentos; 60 min para 4–6.',900,'50 °C'),s('Conservar','Mantén en hielo o −20 °C. Sigue el protocolo específico de transformación.',0,'Hielo / −20 °C')],tips:[{text:'Calcula cantidades de fragmentos con el recurso del fabricante.',url:'https://nebuildercalculator.neb.com/',label:'NEBuilder Calculator'},{text:'Fundamento de ensamblaje isotérmico.',url:'https://doi.org/10.1038/nmeth.1318',label:'Gibson et al., 2009',kind:'Paper'}]},
 {id:'western',manufacturer:'biorad',category:'Western blot',title:'Western blot · Criterion TGX',subtitle:'Transferencia en tanque · EveryBlot + Clarity',tags:['Proteínas','Western blot'],status:'reviewed',source:wb,sourceType:'PDF',version:'Bulletin 7431 · Ver. A',pages:'1–2',duration:'~4 h',description:'Separación, transferencia e inmunodetección de proteínas con el sistema Criterion TGX especificado.',mechanism:'SDS-PAGE separa proteínas; la membrana recibe las bandas y anticuerpos detectan el objetivo.',assumptions:'Condiciones específicas del sistema; no trasladar a otros equipos. Diluciones de anticuerpos dependen del producto.',
 steps:[s('Preparación','Laemmli 1X; prepara 50 % extra.'),s('Calentar','Incuba muestras.',300,'95 °C'),s('Centrifugar','Recoge sobrenadante.',300,'10.000 × g'),s('Electroforesis','Buffer: 400 mL/gel. Carga muestras y ladder; corre hasta el frente. Activa e imagen Stain-Free.',0,'300 V'),s('Equilibrar','Membrana, papeles y almohadillas en buffer.',1200,'Buffer adecuado'),s('Transferir','Monta sándwich, refrigeración y agitación; transfiere y registra imagen.',3600,'100 V'),s('Bloquear','20 mL EveryBlot.',300,'Temperatura ambiente'),s('Primario','Anticuerpo en 20 mL EveryBlot.',3600,'Agitación suave'),...Array.from({length:5},(_,i)=>s(`Lavado primario ${i+1}/5`,'20 mL TBS + Tween 20 al 0,05 %.',300,'Agitación')),
 s('Secundario','Anticuerpo en 20 mL EveryBlot.',3600,'Temperatura ambiente'),...Array.from({length:6},(_,i)=>s(`Lavado secundario ${i+1}/6`,'20 mL TBS + Tween 20 al 0,05 %.',300,'Agitación')),s('Detección','Mezcla 6 + 6 mL Clarity. Incuba membrana.',300,'12 mL'),s('Imagen','Adquiere imagen sin saturación.')],tips:[{text:'Usa el documento para registrar condiciones reales.',url:wb,label:'Checklist del fabricante'}]},
 {id:'quickdna',manufacturer:'zymo',category:'Extracción DNA',title:'Quick-DNA™ Miniprep Plus',subtitle:'Fluidos y células · D4068 / D4069',tags:['Extracción','DNA'],status:'reviewed',source:zymo,sourceType:'PDF',version:'Protocolo rápido · v1.3.0',pages:'1',duration:'~25 min',description:'Purificación en columna de DNA de fluidos y células, con digestión proteica previa.',mechanism:'Lisis, unión a columna, lavados y elución eliminan proteínas e inhibidores.',assumptions:'Esquema para 200 µL. Para menor entrada, escalar buffers según el manual. Consultar preparación de muestra y proteinasa K.',
 steps:[s('Preparar','Hasta 200 µL de muestra + 200 µL BioFluid & Cell Buffer + 20 µL proteinasa K.'),s('Digestión','Mezcla e incuba.',600,'55 °C'),s('Unión','Añade un volumen Genomic Binding Buffer; carga columna IIC-XLR.'),s('Centrifugar','Descarta flujo y cambia tubo.',60,'≥12.000 × g'),s('Prelavar','400 µL DNA Pre-Wash Buffer; centrifuga.',60,'≥12.000 × g'),s('Lavar','700 µL g-DNA Wash Buffer; centrifuga.',60,'≥12.000 × g'),s('Segundo lavado','200 µL g-DNA Wash Buffer; centrifuga.',60,'≥12.000 × g'),s('Eluir','≥50 µL DNA Elution Buffer en tubo limpio.',300,'Incubación'),s('Recoger DNA','Centrifuga.',60,'≥12.000 × g')],tips:[{text:'Verifica los requisitos de preparación de muestra.',url:zymo,label:'Protocolo oficial'}]},
];
const references=[
 ['qiagen','Extracción DNA','QIAprep Spin Miniprep','Plásmidos en columna','https://www.qiagen.com/gh/products/discovery-and-translational-research/dna-rna-purification/dna-purification/plasmid-dna/qiaprep-spin-miniprep-kit','Web'],
 ['qiagen','Extracción DNA','QIAwave Plasmid Miniprep','Handbook · 05/2025','https://www.qiagen.com/by/resources/download.aspx?id=97795874-709c-48b0-96b3-5f9dc0f9275f&lang=en','PDF'],
 ['mn','Extracción DNA','NucleoSpin® Plasmid','Purificación plasmídica · Rev.15 · 11/2024','https://www.mn-net.com/media/pdf/45/51/02/Instruction-NucleoSpin-Plasmid.pdf','PDF'],
 ['agilent','Cloning','QuikChange II','Mutagénesis dirigida','https://www.agilent.com/cs/library/usermanuals/public/200523.pdf','PDF'],
 ['takara','Cloning','In-Fusion Cloning','Manuales y soporte del fabricante','https://help.takarabio.com/36168/kb/category/110155/in-fusion','Web'],
 ['promega','RT-qPCR','GoTaq® 1-Step RT-qPCR','Amplificación a partir de RNA','https://www.promega.com/products/pcr/qpcr-and-rt-qpcr/qpcr-kits/','Web'],
 ['promega','qPCR','GoTaq® Probe qPCR','Detección basada en sonda','https://www.promega.com/products/pcr/qpcr-and-rt-qpcr/qpcr-probe-kits/','Web'],
 ['zymo','Extracción RNA','Quick-DNA/RNA Miniprep','Aislamiento combinado','https://www.zymoresearch.com/products/quick-dna-rna-miniprep','Web'],
 ['thermo','Cultivo celular','DMEM · Guía de uso','Medio basal para células de mamífero','https://assets.thermofisher.com/TFS-Assets/LSG/manuals/MAN0018898_DMEM_IFU.pdf','PDF'],
 ['sigma','Cultivo in vitro','Murashige & Skoog · Salt Base','Cultivo de tejidos vegetales · 56740C','https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/204/492/p56740.pdf','PDF'],
 ['sigma','Cultivo in vitro','Murashige & Skoog · M5519','Medio basal con vitaminas','https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/361/537/m5519pis.pdf','PDF'],
 ['sigma','Microbiología','Medios microbiológicos Sigma','Preparación y especificaciones','https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/148/243/l3152inf.pdf','PDF'],
 ['himedia','Micología','Sabouraud Dextrose Agar · M063A','Agar al 3 % · ficha técnica','https://www.himedialabs.com/media/TD/M063A.pdf','PDF'],
 ['atcc','Cultivo celular','Animal Cell Culture Guide','Células animales y humanas','https://www.atcc.org/resources/culture-guides/animal-cell-culture-guide','Web'],
 ['biorad','Western blot','Western blot · Inmunodetección','Selección de reactivos y recursos','https://www.bio-rad.com/webroot/web/pdf/lsr/literature/Bulletin_7400.pdf','PDF']
];
protocols.push(...references.map((r,i)=>({id:`ref-${i}`,manufacturer:r[0],category:r[1],title:r[2],subtitle:r[3],source:r[4],sourceType:r[5],status:'reference',tags:[r[1]],description:r[3]+'. Referencia localizada; pasos y cálculos pendientes de revisión.',mechanism:'Consulta el documento oficial para el fundamento y las condiciones del producto.',steps:[],tips:[],version:'Referencia oficial',pages:'Consultar fuente'})));
export const media=[
 {id:'lb',category:'Microbiológicos',name:'LB Broth · Miller',manufacturer:'sigma',format:'Polvo comercial',grams:25,source:'https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/148/243/l3152inf.pdf',description:'Medio rico para bacterias de laboratorio. Producto L3152.',preparation:'25 g/L; esterilización según ficha: 121 °C, 15 min. Confirma producto y suplemento.'},
 {id:'lb-agar',category:'Microbiológicos',name:'LB Agar · Miller',manufacturer:'sigma',format:'Polvo comercial',grams:40,source:'https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/148/243/l3152inf.pdf',description:'Medio sólido. Producto L3027.',preparation:'40 g/L; consulta esterilización y suplementos en la ficha.'},
 {id:'luria',category:'Microbiológicos',name:'Luria Broth Base',manufacturer:'sigma',format:'Polvo comercial',grams:15.5,source:'https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/148/243/l3152inf.pdf',description:'Base de medio. Producto L1900.',preparation:'15,5 g/L; preparación según ficha.'},
 {id:'macconkey',category:'Microbiológicos',name:'MacConkey Agar',manufacturer:'sigma',format:'Polvo comercial',grams:50,source:'https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/148/243/l3152inf.pdf',description:'Medio diferencial. Producto M7408.',preparation:'50 g/L; confirma la ficha del producto.'},
 {id:'maltbroth',category:'Hongos',name:'Malt Extract Broth',manufacturer:'sigma',format:'Polvo comercial',grams:15,source:'https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/148/243/l3152inf.pdf',description:'Levaduras y mohos. M6409.',preparation:'15 g/L; consulta ficha.'},
 {id:'maltagar',category:'Hongos',name:'Malt Extract Agar',manufacturer:'sigma',format:'Polvo comercial',grams:33.6,source:'https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/148/243/l3152inf.pdf',description:'Medio sólido para hongos. M6907.',preparation:'33,6 g/L; consulta ficha.'},
 {id:'czapek',category:'Hongos',name:'Czapek Dox Broth',manufacturer:'sigma',format:'Polvo comercial',grams:35,source:'https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/148/243/l3152inf.pdf',description:'Hongos y bacterias. C1551.',preparation:'35 g/L; consulta ficha.'},
 {id:'cornmeal',category:'Hongos',name:'Corn Meal Agar',manufacturer:'sigma',format:'Polvo comercial',grams:17,source:'https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/148/243/l3152inf.pdf',description:'Medio para hongos. C1176.',preparation:'17 g/L; consulta ficha.'},
 {id:'sabouraud',category:'Hongos',name:'Sabouraud Dextrose Agar',manufacturer:'himedia',format:'Referencia · M063A',source:'https://www.himedialabs.com/media/TD/M063A.pdf',description:'Formulación con agar al 3 %. Dosis pendiente de revisión.',preparation:'Ver ficha del producto. No usar dosis de otras variantes.'},
 {id:'ms',category:'Plantas',name:'Murashige & Skoog · 56740C',manufacturer:'sigma',format:'Sales basales',source:'https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/204/492/p56740.pdf',description:'Sales basales sin agar; para tejidos vegetales.',preparation:'Formulación y preparación en PDF. Dosis total pendiente de revisión; no se asume equivalente a M5519.'},
 {id:'msvit',category:'Plantas',name:'MS Basal Medium · M5519',manufacturer:'sigma',format:'Referencia · vitaminas',source:'https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/361/537/m5519pis.pdf',description:'Variante basal para cultivo vegetal.',preparation:'Consultar PDF específico. Añade notas de reguladores de crecimiento según tu sistema.'},
 {id:'dmem',category:'Animales / humanas',name:'DMEM · High glucose',manufacturer:'thermo',format:'Medio basal líquido',source:'https://www.thermofisher.com/de/de/home/technical-resources/media-formulation.8.html',description:'Formulación 11965. Glucosa 4,5 g/L y glutamina 4 mM.',preparation:'Suplementos según línea celular. No se presupone una concentración universal de suero.'},
 {id:'atccmedia',category:'Animales / humanas',name:'Selección de medio · ATCC',manufacturer:'atcc',format:'Guía de selección',source:'https://www.atcc.org/resources/culture-guides/animal-cell-culture-guide',description:'Referencia para selección y mantenimiento de células de mamífero.',preparation:'Usa las condiciones de la ficha de tu línea celular.'}
];
export const compounds=[
 {id:'nacl',name:'Cloruro de sodio',formula:'NaCl',mw:58.44},
 {id:'tris',name:'Tris base',formula:'C₄H₁₁NO₃',mw:121.14},
 {id:'tris-hcl',name:'Tris-HCl',formula:'C₄H₁₂ClNO₃',mw:157.60},
 {id:'edta',name:'EDTA disódico dihidrato',formula:'C₁₀H₁₄N₂Na₂O₈·2H₂O',mw:372.24},
 {id:'glucose',name:'D-Glucosa anhidra',formula:'C₆H₁₂O₆',mw:180.16},
 {id:'sucrose',name:'Sacarosa',formula:'C₁₂H₂₂O₁₁',mw:342.30},
 {id:'kcl',name:'Cloruro de potasio',formula:'KCl',mw:74.55},
 {id:'mgcl2',name:'Cloruro de magnesio hexahidrato',formula:'MgCl₂·6H₂O',mw:203.30},
 {id:'cacl2',name:'Cloruro de calcio dihidrato',formula:'CaCl₂·2H₂O',mw:147.02},
 {id:'hepes',name:'HEPES',formula:'C₈H₁₈N₂O₄S',mw:238.30},
 {id:'kh2po4',name:'Fosfato monopotásico',formula:'KH₂PO₄',mw:136.09},
 {id:'k2hpo4',name:'Fosfato dipotásico anhidro',formula:'K₂HPO₄',mw:174.18},
 {id:'sds',name:'Dodecil sulfato de sodio',formula:'C₁₂H₂₅NaO₄S',mw:288.38},
 {id:'urea',name:'Urea',formula:'CH₄N₂O',mw:60.06},
 {id:'nahco3',name:'Bicarbonato de sodio',formula:'NaHCO₃',mw:84.01}
];
export const categories=[...new Set(protocols.map(p=>p.category))];
// Parameters reviewed from the locally extracted manufacturer PDF, 2026-10-01.
Object.assign(protocols.find(p=>p.id==='ref-10'),{
 status:'reviewed',duration:'~30 min',version:'M5519 · ficha de producto',pages:'1',
 description:'Medio vegetal basal con macroelementos, microelementos y vitaminas. El producto M5519 requiere 4,4 g/L; suplementos según cultivo.',
 mechanism:'Aporta nutrientes minerales y vitaminas al explante. Los reguladores de crecimiento y agentes gelificantes dependen del sistema vegetal.',
 assumptions:'Usa la dosis exacta de M5519. El pH 5,7 ± 0,1 es un ejemplo del fabricante. Los suplementos termolábiles se añaden después de la esterilización.',
 steps:[s('Preparar agua','Mide aproximadamente 90 % del volumen final; usa un recipiente del doble de capacidad.'),s('Disolver polvo','Añade M5519 a 4,4 g/L mientras agitas. Enjuaga el envase y reúne el líquido.'),s('Suplementar','Añade los suplementos apropiados para tu cultivo.'),s('Ajustar pH','Ajusta al pH validado, por ejemplo 5,7 ± 0,1.'),s('Completar volumen','Añade agua hasta volumen final. Si hay gelificante, calienta hasta claridad.'),s('Esterilizar','Distribuye según aplicación y usa autoclave validada; el medio debe alcanzar estas condiciones.',900,'121 °C · 15 psi'),s('Terminar','Añade componentes termolábiles asépticamente tras esterilizar. Almacena preparado según ficha.',0,'2–8 °C')],
 tips:[{text:'No preparar concentrado: pueden precipitar sales.',url:'https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/361/537/m5519pis.pdf',label:'Ficha M5519'}]
});
Object.assign(media.find(m=>m.id==='ms'),{grams:4.302,format:'Polvo · sales basales',preparation:'Producto 56740C: 4,302 g/L. Disuelve en 80–90 % del volumen de agua a 15–30 °C; añade suplementos compatibles según ficha.'});
Object.assign(media.find(m=>m.id==='msvit'),{grams:4.4,format:'Polvo · medio con vitaminas',preparation:'Producto M5519: 4,4 g/L. pH según aplicación (ejemplo 5,7 ± 0,1). El medio debe alcanzar 121 °C durante al menos 15 min en autoclave validada. Suplementos termolábiles después; preparado a 2–8 °C.'});
Object.assign(media.find(m=>m.id==='sabouraud'),{grams:80,format:'Polvo · M063A · agar al 3 %',description:'Variante de agar al 3 % para levaduras y mohos. Dosis específica M063A.',preparation:'M063A: 80 g/L. Disuelve con calor, esteriliza a 121 °C durante 15 min; enfría a 45–50 °C antes de verter. pH final 5,6 ± 0,2. No usar esta dosis para M063.'});
protocols.find(p=>p.id==='western').duration='~5 h';
