// SheetJS CE is vendored for the browser: no server receives sample files.
const engine=X=>{if(!X?.utils)throw new Error('La biblioteca Excel aún no está disponible. Recarga la app.');return X;};
export function readSampleWorkbook(bytes,X=globalThis.XLSX){
 engine(X);const book=X.read(bytes,{type:'array',cellFormula:false,cellHTML:false,sheetRows:10002});
 const sheets=book.SheetNames.map(name=>({name,rows:X.utils.sheet_to_json(book.Sheets[name],{header:1,defval:'',raw:true,blankrows:true})}));
 if(!sheets.length)throw new Error('El archivo no contiene hojas.');return sheets;
}
function worksheet(rows,X){const s=X.utils.aoa_to_sheet(rows);s['!cols']=rows[0].map((_,i)=>({wch:Math.min(70,Math.max(18,...rows.slice(0,80).map(r=>String(r[i]??'').length+2)))}));s['!autofilter']={ref:s['!ref']};return s;}
function file(book,X){return X.write(book,{type:'array',bookType:'xlsx',compression:true});}
export function sampleTemplate(X=globalThis.XLSX){engine(X);const b=X.utils.book_new();X.utils.book_append_sheet(b,worksheet([['Muestra','Concentración (ng/µL)'],['A',100],['B',80],['C',50],['D',125]],X),'Concentraciones');return file(b,X);}
export function digestWorkbook(c,r,X=globalThis.XLSX){
 engine(X);const b=X.utils.book_new();const conditionRows=[['Parámetro','Valor','Unidad / detalle'],['Fabricante',r.vendor.name,''],['Buffer',r.buffer.name,''],['Volumen final',r.volume,'µL'],['DNA objetivo',r.target,r.mode==='pool'?'ng totales del pool':'ng por muestra'],['Buffer stock',r.buffer.stock,'X'],['Buffer final',r.buffer.final,'X'],['BSA acetilada',r.bsaVolume,'µL · stock 10 µg/µL'],...Array.from({length:3},(_,i)=>['Enzima '+(i+1),r.enzymes[i]?.volume||0,'µL · '+(r.enzymes[i]?.name||'Sin enzima')]),['Modo',r.mode,'batch = tubos independientes; pool = mezcla física con igual masa de cada muestra'],['Temperatura',r.temperature,'°C'],['Incubación',r.minutes,'min'],['Exceso mezcla común',Number(c.excess)||0,'%'],['Notas',c.notes||'',''],['Color del buffer',r.buffer.color,''],['Fuente de receta',r.vendor.source,''],['Fuente compatibilidad',r.vendor.compatibility,''],['Compatibilidad al exportar',[...r.errors,...r.warnings].join('; ')||'Sin incidencias en la configuración exportada','Reevaluar en Molab si cambias las enzimas o el buffer.'],['Programa',c.name,'Molab 2.5.0 · '+new Date().toISOString()]];
 for(const en of r.enzymes)conditionRows.push([en.name+' stock',en.stock??'No indicado',r.vendor.id==='thermo'?'Dosis FastDigest; no equivale a U convencionales':'U/µL introducidas por el usuario']);
 conditionRows.push(['Buffer recomendado',r.recommendation.best.name,r.recommendation.best.final+'X final']);
 for(const en of r.enzymes){const value=en.activities[r.buffer.id],optimal=r.vendor.buffers.find(b=>b.id===en.recommendedBuffer);conditionRows.push([en.name+' actividad en buffer elegido',value===undefined?'Sin datos':value,value==='NR'?'No recomendado por el fabricante':'% · rango publicado'+((en.star||[]).includes(r.buffer.id)?' · actividad star':'' )]);if(optimal)conditionRows.push([en.name+' buffer individual',optimal.name,optimal.final+'X · '+optimal.color]);conditionRows.push([en.name+' fuente',en.manual||en.product||en.source,'Ficha / matriz del producto']);}
 const conditions=worksheet(conditionRows,X);
 const columns=['Muestra','Concentración (ng/µL)','DNA (ng)','DNA (µL)','Buffer (µL)','BSA (µL)',...Array.from({length:3},(_,i)=>(r.enzymes[i]?.name||'Enzima '+(i+1))+' (µL)'), 'Agua (µL)','Volumen final (µL)','Estado','Medición original','Unidad original','Fila de origen'];
 const rows=[columns,...r.rows.map(s=>[s.name,s.concentration??s.input?.concentration??'',s.mass,s.dna,r.mode==='pool'?'':r.bufferVolume,r.mode==='pool'?'':r.bsaVolume,...Array.from({length:3},(_,j)=>r.mode==='pool'?'':r.enzymes[j]?.volume||0),r.mode==='pool'?'':s.water,r.mode==='pool'?'':r.volume,s.error||'Calculado',s.input?.rawConcentration??s.input?.concentration??'',''+(s.input?.sourceUnit||'ng/µL'),s.input?.sourceRow??''])];
 const results=worksheet(rows,X),ref=(row)=>"'Condiciones'!$B$"+row;
 function formula(cell,f,v){results[cell]={t:typeof v==='string'?'s':'n',f,v,z:typeof v==='number'?'0.0000':undefined};}
 r.rows.forEach((s,i)=>{const row=i+2;if(s.error)return;formula('C'+row,r.mode==='pool'?ref(5)+'/'+r.rows.length:ref(5),s.mass);formula('D'+row,`IF(AND(ISNUMBER(B${row}),B${row}>0),C${row}/B${row},0)`,s.dna);if(r.mode==='pool'){formula('L'+row,`IF(AND(ISNUMBER(B${row}),B${row}>0),"Calculado","Concentracion invalida")`,'Calculado');return;}
  formula('E'+row,ref(4)+'*'+ref(7)+'/'+ref(6),r.bufferVolume);formula('F'+row,ref(8),r.bsaVolume);['G','H','I'].forEach((col,j)=>formula(col+row,ref(9+j),r.enzymes[j]?.volume||0));formula('K'+row,ref(4),r.volume);formula('J'+row,`K${row}-SUM(D${row}:I${row})`,s.water);
  formula('L'+row,`IF(AND(ISNUMBER(B${row}),B${row}>0),IF(J${row}<0,"Agua negativa",IF(SUM(G${row}:I${row})>K${row}/10,"Enzimas >10%","Calculado")),"Concentracion invalida")`,'Calculado');
 });
 if(r.mode==='pool'){
  const i=rows.length+1,end=rows.length,water=r.poolWater??0;rows.push(['POOL','','',r.poolDna??0,r.bufferVolume,r.bsaVolume,...Array.from({length:3},(_,j)=>r.enzymes[j]?.volume||0),water,r.volume,r.valid?'Calculado':r.errors.join('; ')]);
  const aggregate=worksheet(rows,X);Object.assign(aggregate,results);aggregate['!ref']=X.utils.encode_range({s:{r:0,c:0},e:{r:i-1,c:columns.length-1}});aggregate['!autofilter']={ref:aggregate['!ref']};
  aggregate['D'+i]={t:'n',f:`SUM(D2:D${end})`,v:r.poolDna??0,z:'0.0000'};aggregate['E'+i]={t:'n',f:ref(4)+'*'+ref(7)+'/'+ref(6),v:r.bufferVolume,z:'0.0000'};aggregate['F'+i]={t:'n',f:ref(8),v:r.bsaVolume,z:'0.0000'};['G','H','I'].forEach((col,j)=>aggregate[col+i]={t:'n',f:ref(9+j),v:r.enzymes[j]?.volume||0,z:'0.0000'});aggregate['K'+i]={t:'n',f:ref(4),v:r.volume,z:'0.0000'};aggregate['J'+i]={t:'n',f:`K${i}-SUM(D${i}:I${i})`,v:water,z:'0.0000'};aggregate['L'+i]={t:'s',f:`IF(COUNTIFS(L2:L${end},"Concentracion invalida")>0,"Concentracion invalida",IF(J${i}<0,"Agua negativa",IF(SUM(G${i}:I${i})>K${i}/10,"Enzimas >10%","Calculado")))`,v:r.valid?'Calculado':r.errors.join('; ')};X.utils.book_append_sheet(b,aggregate,'Digestiones');
 }else X.utils.book_append_sheet(b,results,'Digestiones');
 X.utils.book_append_sheet(b,conditions,'Condiciones');b.Workbook={CalcPr:{calcMode:'auto'}};b.Props={Title:c.name,Author:'Molab Studio',Subject:'Cálculos de digestión de DNA'};return file(b,X);
}
export function programWorkbook(title,program,cycles,X=globalThis.XLSX){engine(X);const b=X.utils.book_new();const rows=[['Fase','Temperatura (°C)','Duración (s)','Repeticiones','Tipo'],...program.map(t=>[t.label,Number(t.temp),Number(t.seconds),t.repeat?Number(cycles):1,t.seconds===0?'Sin duración fija':t.repeat?'Bloque repetido':'Una vez'])];X.utils.book_append_sheet(b,worksheet(rows,X),'Programa');X.utils.book_append_sheet(b,worksheet([['Parámetro','Valor'],['Protocolo',title],['Ciclos del bloque',Number(cycles)],['Versión','Molab 2.5.0'],['Nota','Programar las fases repetidas como un único bloque en el orden indicado. 0 s = conservación o duración sin fijar. Las rampas y tapa se configuran en el equipo.']],X),'Configuración');return file(b,X);}
