import {literature} from './literature-data.js?v=2.3.0';
export const extraSources=[{id:'pubmed',name:'Literatura · PubMed',short:'PM',color:'#346487',url:'https://pubmed.ncbi.nlm.nih.gov/'},{id:'goldenbraid',name:'GoldenBraid · IBMCP',short:'GB',color:'#bd9238',url:'https://goldenbraidpro.com/'},{id:'addgene',name:'Addgene',short:'AG',color:'#ae4962',url:'https://www.addgene.org/protocols/'},{id:'phytotech',name:'PhytoTech Labs',short:'PT',color:'#568460',url:'https://phytotechlab.com/technical-info'}];
const refs=[
 ['gb-domestication','GoldenBraid 2.0 · domesticación','Retirada de sitios internos y creación de GBparts','https://goldenbraidpro.com/files/documents/GB2.0_Users_manual.pdf','goldenbraid','La domesticación prepara las partes para la gramática GB2.0.'],
 ['gb-multipartite','GoldenBraid 2.0 · ensamblaje multipartito','Partes básicas → unidad transcripcional · α / Ω','https://goldenbraidpro.com/files/documents/GB2.0_Users_manual.pdf','goldenbraid','Une partes estandarizadas en una unidad transcripcional.'],
 ['gb-binary','GoldenBraid 2.0 · ensamblaje binario','Unidades transcripcionales → construcciones multigénicas','https://goldenbraidpro.com/files/documents/GB2.0_Users_manual.pdf','goldenbraid','Combina dos módulos compatibles, alternando niveles α y Ω.'],
 ['gb-fungal','FungalBraid · GoldenBraid para hongos','Protocolo publicado · Current Protocols 2020','https://doi.org/10.1002/cpmb.116','pubmed','Adaptación de GoldenBraid a hongos filamentosos.'],
 ['gb4','GB4.0 · herramientas CRISPR en plantas','Plataforma de ensamblaje modular','https://pmc.ncbi.nlm.nih.gov/articles/PMC8284049/','goldenbraid','Plataforma modular para combinar componentes de edición vegetal.'],
 ['greengate2','GreenGate 2.0','Extensiones compatibles con GreenGate','https://pmc.ncbi.nlm.nih.gov/articles/PMC10490876/','pubmed','Amplía las unidades transcripcionales y su apilamiento.'],
 ['greengate','GreenGate','Módulos para construcciones vegetales','https://doi.org/10.1371/journal.pone.0083043','pubmed','Ensamblaje de módulos vegetales mediante BsaI.'],
 ['loop','Loop Assembly','Ensamblaje recursivo','https://pubmed.ncbi.nlm.nih.gov/30521109/','pubmed','Organiza construcciones de DNA de manera recursiva.'],
 ['uloop','Universal Loop Assembly','uLoop · ensamblaje entre sistemas','https://pmc.ncbi.nlm.nih.gov/articles/PMC7052795/','pubmed','Extiende Loop a contextos de distintos reinos.'],
 ['mobius','Mobius Assembly','Golden Gate jerárquico · BsaI / AarI','https://doi.org/10.1371/journal.pone.0189892','pubmed','Alterna dos niveles de ensamblaje e incorpora AarI.'],
 ['moclo','MoClo · protocolo jerárquico','Partes → unidades transcripcionales → multigenes','https://doi.org/10.1002/cpmb.115','pubmed','Estandariza ensamblajes Golden Gate en niveles.'],
 ['basic','BASIC Assembly','Biopart assembly standard','https://pubmed.ncbi.nlm.nih.gov/25746445/','pubmed','Estándar modular de ensamblaje de partes.'],
 ['dash','DASH · apilamiento de genes vegetales','Sistema publicado de alta capacidad','https://pmc.ncbi.nlm.nih.gov/articles/PMC12392928/','pubmed','Sistema de ensamblaje y apilamiento de genes.'],
 ['gg-sapi','SapI · Start/Stop compatible con MoClo','Protocolo publicado · preprint identificado','https://arxiv.org/abs/2402.03410','pubmed','Ensamblaje de unidades mediante extremos de tres bases.'],
 ['gg-txtl','Golden Gate · plantillas lineales TXTL','Protocolo publicado · preprint identificado','https://arxiv.org/abs/2310.13665','pubmed','Construcción de plantillas para prototipado sin células.']
];
export const curatedProtocols=refs.map(([id,title,subtitle,source,manufacturer,mechanism])=>({id,category:'Cloning',title,subtitle,source,manufacturer,mechanism,sourceType:source.endsWith('.pdf')?'PDF':'Artículo',status:'reference',tags:['Cloning',...( /GoldenBraid|GreenGate|Loop|Mobius|MoClo|SapI|DASH/.test(title)?['Type IIS']:[])],description:subtitle+'. Ficha de orientación; consulta materiales, condiciones y controles del documento original.',steps:[],tips:[{text:mechanism,url:source,label:'Fuente primaria',kind:'Paper'}],version:'Documento original',pages:'Consulta el documento'}));
const startStop='https://pmc.ncbi.nlm.nih.gov/articles/PMC6379671/';
curatedProtocols.push({id:'start-stop',doi:'10.1093/nar/gky1182',manufacturer:'pubmed',category:'Cloning',title:'Start-Stop Assembly · reacción de ensamblaje',subtitle:'SapI / BsaI / BbsI según nivel · Taylor et al.',source:startStop,sourceType:'Artículo',status:'reviewed',version:'NAR · gky1182 · métodos',pages:'Start-Stop Assembly reactions',duration:'~5 h 20 min',tags:['Cloning','Type IIS','Start-Stop'],description:'Ensamblaje modular con extremos de tres bases en límites de CDS. Esta guía cubre la reacción, no la transformación.',mechanism:'La digestión y ligación cíclicas ensamblan partes compatibles; el enzima depende del nivel.',assumptions:'20 fmol de vector y 40 fmol de cada inserto. Introduce el volumen real de tus DNAs y enzimas según su concentración; la calculadora molar permite obtenerlo. Buffer T4 a 1X. No intercambiar niveles o enzimas.',volume:20,cycles:30,components:[{name:'Buffer T4 DNA ligasa 10X',volume:2}],thermal:[{label:'Restricción',temp:37,seconds:300,repeat:true},{label:'Ligación',temp:16,seconds:300,repeat:true},{label:'Inactivación',temp:65,seconds:1200}],steps:[{title:'Verificar nivel y partes',text:'Comprueba la gramática, el vector receptor y el enzima correspondiente: SapI, BsaI o BbsI.',seconds:0,conditions:'Diseño validado'},{title:'Configurar volúmenes',text:'Añade a la configuración cada DNA (20 fmol vector; 40 fmol por inserto), T4 ligasa (400 U) y restricción (10 U) con sus volúmenes reales. Completa a 20 µL.',seconds:0,conditions:'Buffer T4 1X'},{title:'Termociclado',text:'Ejecuta el programa de restricción y ligación.',seconds:0,conditions:'Programa configurado'},{title:'Registrar y continuar',text:'Registra el ensamblaje. Consulta el protocolo de transformación y comprobación de clones del sistema empleado.',seconds:0,conditions:'Verificación independiente'}],tips:[{text:'La identidad de la endonucleasa cambia entre niveles; confirma el esquema en el artículo.',url:startStop,label:'Métodos Start-Stop',kind:'Paper'}]});
export const indexedProtocols=literature.map(r=>({id:r.id,manufacturer:'pubmed',category:r.category,title:r.title,subtitle:[r.method,r.journal,r.year].filter(Boolean).join(' · '),source:r.source,sourceType:'PubMed',status:'reference',tags:r.tags,version:r.doi?'DOI '+r.doi:'PMID '+r.pmid,pages:'Metadatos indexados',description:'Registro bibliográfico asociado a «'+r.method+'». '+(r.authors?'Autores: '+r.authors+'. ':'')+'Indexado por búsqueda dirigida; el texto completo y sus condiciones experimentales no han sido revisados.',mechanism:'El registro permite localizar la publicación original. La pertenencia a una búsqueda no valida el mecanismo ni constituye una receta experimental.',steps:[],tips:[{text:'Consulta métodos y suplementos en la publicación original; confirma modelo biológico, producto, controles y versión antes de crear una adaptación.',url:r.source,label:r.journal||'PubMed',kind:'Paper'}],bibliography:r}));
export const hormoneSource='https://www.sigmaaldrich.com/IE/en/technical-documents/technical-article/cell-culture-and-cell-culture-analysis/plant-tissue-culture/growth-regulators';
export const phytoSource='https://phytotechlab.com/media/documents/ProductLiterature/PlantGrowthRegulators.pdf';
export const extraCompounds=[
 {id:'iaa',name:'IAA · ácido indol-3-acético libre',formula:'C₁₀H₉NO₂',mw:175.18,cas:'87-51-4',product:'Sigma I2886',solvent:'Etanol o NaOH 1 N',diluent:'Agua',preparation:'Predisolver; después completar con agua. La sal sódica tiene otra preparación.',preparationSource:hormoneSource,sds:'https://www.sigmaaldrich.com/IE/en/product/sigma/i2886'},
 {id:'iaa-na',name:'IAA · sal sódica',formula:'C₁₀H₈NNaO₂',mw:197.17,cas:'6505-45-9',product:'Sigma I5148',solvent:'Agua',diluent:'Agua',preparation:'Disolver en agua; no aplicar la receta del ácido libre.',preparationSource:hormoneSource,sds:'https://b2b.sigmaaldrich.com/US/en/product/sigma/i5148'},
 {id:'iba',name:'IBA · ácido indol-3-butírico',formula:'C₁₂H₁₃NO₂',mw:203.24,cas:'133-32-4',product:'Sigma I5386',solvent:'Etanol o NaOH 1 N',diluent:'Agua',preparation:'Predisolver antes de completar con agua.',preparationSource:hormoneSource,sds:'https://www.sigmaaldrich.com/sds/sigma/i5386'},
 {id:'naa',name:'NAA · ácido naftalenacético libre',formula:'C₁₂H₁₀O₂',mw:186.21,cas:'86-87-3',product:'Sigma N0640',solvent:'NaOH 1 N',diluent:'Agua',preparation:'Predisolver en NaOH 1 N; después completar con agua.',preparationSource:hormoneSource,sds:'https://www.sigmaaldrich.com/US/en/sds/sigma/n0640'},
 {id:'noa',name:'NOA · ácido naftoxiacético',formula:'C₁₂H₁₀O₃',mw:202.21,cas:'120-23-0',product:'Sigma N3019',solvent:'NaOH 1 N',diluent:'Agua',preparation:'Predisolver y completar con agua.',preparationSource:hormoneSource,sds:'https://www.sigmaaldrich.com/IE/en/product/sigma/n3019'},
 {id:'bap',name:'BAP · 6-benzilaminopurina',formula:'C₁₂H₁₁N₅',mw:225.25,cas:'1214-39-7',product:'PhytoTech B800',solvent:'KOH 1 N',diluent:'Según ficha de stock',preparation:'Disolvente de referencia: KOH 1 N. Confirmar diluyente del stock.',preparationSource:phytoSource,sds:'https://phytotechlab.com/6-benzylaminopurine-ba.html'},
 {id:'kinetin',name:'Kinetina',formula:'C₁₀H₉N₅O',mw:215.21,cas:'525-79-1',product:'PhytoTech K750',solvent:'KOH 1 N',diluent:'Agua',preparation:'Predisolver en KOH 1 N; diluir en agua.',preparationSource:phytoSource,sds:'https://phytotechlab.com/kinetin.html'},
 {id:'ga3',name:'GA₃ · ácido giberélico',formula:'C₁₉H₂₂O₆',mw:346.38,cas:'77-06-5',product:'PhytoTech G500',solvent:'Etanol',diluent:'Según ficha de stock',preparation:'Preparar stock en etanol; verificar compatibilidad con el medio.',preparationSource:phytoSource,sds:'https://phytotechlab.com/gibberellic-acid-ga3.html'},
 {id:'tdz',name:'Thidiazuron · TDZ',formula:'C₉H₈N₄OS',mw:220.25,cas:'51707-55-2',product:'PhytoTech T888',solvent:'DMSO',diluent:'Según ficha de stock',preparation:'Preparar stock en DMSO.',preparationSource:phytoSource,sds:'https://phytotechlab.com/thidiazuron.html'},
 {id:'zeatin',name:'Zeatina · Z125',formula:'C₁₀H₁₃N₅O',mw:219.24,cas:'1637-39-4',product:'PhytoTech Z125',solvent:'KOH 1 N',diluent:'Agua',preparation:'Predisolver en KOH 1 N; diluir en agua.',preparationSource:phytoSource,sds:'https://phytotechlab.com/zeatin.html'},
 {id:'2ip',name:'2iP · 6-(γ,γ-dimetilalilamino)purina',formula:'C₁₀H₁₃N₅',mw:203.24,cas:'2365-40-4',product:'PhytoTech D525',solvent:'KOH 1 N',diluent:'Agua',preparation:'Predisolver en KOH 1 N; diluir en agua.',preparationSource:phytoSource,sds:'https://phytotechlab.com/6-gamma-gamma-dimethylallylamino-purine-2ip.html'},
 {id:'naoh',name:'Hidróxido de sodio anhidro',formula:'NaOH',mw:40,cas:'1310-73-2',product:'Sigma S5881',solvent:'Agua',diluent:'Agua',preparation:'Preparación exotérmica: añadir sólido gradualmente al agua con agitación y enfriamiento. Dejar enfriar antes de aforar.',preparationSource:'https://www.sigmaaldrich.com/IE/en/product/sigald/s5881',sds:'https://www.sigmaaldrich.com/IE/en/product/sigald/s5881',hazards:'H290: puede corroer metales. H314: quemaduras graves en piel y lesiones oculares.',safety:'Protección ocular y cutánea, guantes compatibles; controlar calentamiento y salpicaduras.',safetyStatus:'Clasificación verificada en ficha de producto'},
 {id:'dmso',name:'Dimetilsulfóxido · DMSO',formula:'C₂H₆OS',mw:78.13,cas:'67-68-5',product:'Sigma D8418',solvent:'Líquido miscible con agua',diluent:'Según aplicación',preparation:'Para filtración, la ficha recomienda membrana PTFE o nylon; no acetato de celulosa.',preparationSource:'https://b2b.sigmaaldrich.com/US/en/product/sigma/d8418',sds:'https://b2b.sigmaaldrich.com/US/en/product/sigma/d8418',safety:'Líquido combustible. Protección ocular y guantes compatibles. Punto de inflamación de la ficha: 87 °C.',safetyStatus:'Datos de ficha de producto; revisar SDS local'}
];
export const compoundDetails={edta:{solvent:'Agua; ajuste de pH a ~8 para stock concentrado',diluent:'Agua',preparation:'EDTA disódico no se disuelve completamente en el stock concentrado hasta ajustar aproximadamente a pH 8 con NaOH. Confirmar forma dihidrato y receta.',preparationSource:'https://stuparlab.cfans.umn.edu/protocols/common-solutions',sds:'https://www.sigmaaldrich.com/ES/es/search/edta?focus=products&page=1&perpage=30&sort=relevance&term=edta&type=product'},tris:{solvent:'Agua',diluent:'Agua',preparation:'Disolver Tris base en una fracción del volumen; ajustar pH con HCl según receta y temperatura; completar al volumen final.',preparationSource:'https://stuparlab.cfans.umn.edu/protocols/common-solutions'},sds:{sds:'https://www.sigmaaldrich.com/US/en/product/sigma/l3771'}};
const plantMedia='https://phytotechlab.com/media/documents/ProductLiterature/MediaFormulations.pdf';
const microbialMedia='https://www.sigmaaldrich.com/AM/en/technical-documents/technical-article/cell-culture-and-cell-culture-analysis/microbial-cell-culture/microbial-media';
const cellMedia='https://www.thermofisher.com/kr/ko/home/life-science/cell-culture/mammalian-cell-culture/cell-culture-media.html';
export const extraMedia=[
 ...['Gamborg B-5 basal','Gamborg · sales basales','Gamborg PRL-4-DM','Gresshoff & Doy','Hoagland modificado','Heller','Heller / White modificado','Lloyd & McCown · Woody Plant'].map((name,i)=>({id:'plant-extra-'+i,name,category:'Plantas',manufacturer:'phytotech',format:'Formulación de referencia',source:plantMedia,description:'Medio vegetal: consultar formulación y referencia comercial.',preparation:'Selecciona la referencia exacta en el PDF. Las concentraciones, vitaminas y suplementos varían; usa el constructor de buffers y medios con una receta validada.'})),
 ...['RPMI 1640','IMDM','Ham’s F-12','DMEM / F-12'].map((name,i)=>({id:'cell-extra-'+i,name,category:'Animales / humanas',manufacturer:'thermo',format:'Familia de medios',source:cellMedia,description:'Medio basal de cultivo celular; existen variantes por producto.',preparation:'Verifica el catálogo de tu producto: bicarbonato, glutamina, glucosa, pH y suplementación dependen de la formulación y del modelo celular.'})),
 {id:'sob',name:'SOB · Hanahan’s Broth H8032',category:'Microbiológicos',manufacturer:'sigma',format:'Polvo H8032',grams:28,source:microbialMedia,description:'Medio rico de referencia para trabajo con bacterias de laboratorio.',preparation:'H8032: 28 g/L. Preparar, esterilizar y enfriar según ficha comercial.'},
 {id:'soc',name:'SOC · S1797',category:'Microbiológicos',manufacturer:'sigma',format:'Líquido listo para usar',source:microbialMedia,description:'Medio de recuperación; producto líquido de referencia.',preparation:'S1797 listo para usar. Consulta almacenamiento y compatibilidad con tu cepa.'},
 {id:'tb',name:'Terrific Broth modificado · T9179',category:'Microbiológicos',manufacturer:'sigma',format:'EZMix T9179',grams:48.2,source:microbialMedia,description:'Medio rico de referencia comercial.',preparation:'T9179: 48,2 g/L, con 4 mL/L de glicerol. Preparar y esterilizar según ficha.'},
 {id:'m9',name:'M9 · sales mínimas',category:'Microbiológicos',manufacturer:'sigma',format:'Formulación de referencia',source:microbialMedia,description:'Familia de medios mínimos.',preparation:'La base de sales requiere suplementos específicos. Comprueba producto, fuente de carbono y sales antes de preparar.'},
 {id:'malt-himedia',name:'Malt Agar · 2 % agar M253F',category:'Hongos',manufacturer:'himedia',format:'Referencia comercial',source:'https://www.himedialabs.com/us/m253f-malt-agar-w-2-agar.html',description:'Medio para levaduras y mohos.',preparation:'Dosis y preparación según TD de M253F. No aplicar la dosis de otra variante de Malt Agar.'}
];
const ss=curatedProtocols.find(p=>p.id==='start-stop');
ss.components.push({name:'Vector · 20 fmol (introducir µL)',volume:0,template:true,required:true},{name:'Inserto · 40 fmol (introducir µL; suma si varios)',volume:0,template:true,required:true},{name:'T4 ligasa · 400 U (introducir µL)',volume:0,required:true},{name:'Enzima Type IIS · 10 U (introducir µL)',volume:0,required:true});
Object.assign(extraCompounds.find(c=>c.id==='iba'),{hazards:'H301: tóxico en caso de ingestión.',safety:'GHS06 · peligro. Evitar ingestión y exposición al polvo; protección ocular y guantes. Gestión de residuos conforme a SDS.',safetyStatus:'Clasificación de producto Sigma I5386 verificada',sds:'https://www.sigmaaldrich.com/US/en/product/sigma/i5386'});
Object.assign(extraCompounds.find(c=>c.id==='naa'),{hazards:'H302 · H315 · H318 · H335 · H412: nocivo por ingestión; irritación cutánea y respiratoria; daño ocular grave; efectos acuáticos duraderos.',safety:'Evitar polvo y vertidos; protección ocular y guantes. Revisar sección 4 de SDS para primeros auxilios.',safetyStatus:'Clasificación de producto Sigma N0640 verificada',sds:'https://www.sigmaaldrich.com/JP/en/product/sigma/n0640'});
Object.assign(extraCompounds.find(c=>c.id==='naoh'),{preparationSource:'https://www.sigmaaldrich.com/DE/de/product/sigald/a1010'});
Object.assign(compoundDetails.sds,{cas:'151-21-3',product:'Sigma L3771',hazards:'H228 · H302+H332 · H315 · H318 · H335 · H412: sólido inflamable; nocivo por ingestión o inhalación; irritación; daño ocular grave; peligro acuático.',safety:'Evitar polvo, calor y fuentes de ignición; protección ocular y guantes; evitar vertidos.',safetyStatus:'Clasificación de referencia Sigma L3771 verificada',sds:'https://www.sigmaaldrich.com/SE/en/product/sigma/l3771'});
extraCompounds.push({...extraCompounds.find(c=>c.id==='bap'),id:'bap-sigma',name:'BAP · Sigma B3408 · ficha de seguridad',product:'Sigma B3408',solvent:'Confirmar preparación para B3408',diluent:'Según ficha',preparation:'Consultar la preparación específica de B3408; no trasladar automáticamente la receta del producto B800.',preparationSource:'https://www.sigmaaldrich.com/US/en/product/sigma/b3408',hazards:'H302 · H361fd · H410: nocivo por ingestión; sospecha de daño a fertilidad/feto; peligro acuático duradero.',safety:'GHS07 · GHS08 · GHS09. Evitar exposición, polvo y vertidos; protección ocular y guantes. Revisar SDS del país y producto.',safetyStatus:'Clasificación en ficha de producto B3408 verificada; revisar diferencias entre revisiones SDS',sds:'https://www.sigmaaldrich.com/US/en/product/sigma/b3408'});
