import {emptyDocument,validateDocument,mergeDocuments} from './sync-data.js?v=2.5.0';
const API='https://api.github.com',FILE='molab/personal-v1.json',MAX=5*1024*1024;
export const encodeUTF8=text=>{const bytes=new TextEncoder().encode(text);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary);};
export const decodeUTF8=content=>new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(atob(content.replace(/\s/g,'')),c=>c.charCodeAt(0)));
export function repositoryName(value){const name=String(value||'').trim().replace(/^https:\/\/github\.com\//,'').replace(/\/$/,'');if(!/^[a-z\d](?:[a-z\d-]{0,38})\/[a-z\d_.-]{1,100}$/i.test(name)||/[.]{2}/.test(name))throw new Error('Introduce el repositorio como usuario/nombre.');return name;}
export class GitHubSync {
 constructor({repository,token,fetcher=globalThis.fetch}){this.repository=repositoryName(repository);this.token=String(token||'').trim();if(this.token.length<20||/\s/.test(this.token))throw new Error('Introduce un token de GitHub válido.');this.fetcher=fetcher;}
 async request(path,{method='GET',body,missing=false}={}){let response;try{response=await this.fetcher(API+path,{method,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+this.token,'X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},cache:'no-store',credentials:'omit',redirect:'error',signal:AbortSignal.timeout(20000),...(body?{body:JSON.stringify(body)}:{})});}catch{throw new Error('No se pudo conectar con GitHub. Los cambios siguen guardados en este dispositivo.');}if(missing&&response.status===404)return null;if(!response.ok){const message=({401:'Token inválido o caducado. Vuelve a conectar.',403:'GitHub ha rechazado el acceso. Revisa Contents: lectura y escritura, caducidad y límites de uso.',404:'No se encuentra el repositorio privado. Revisa el nombre y los repositorios permitidos por el token.',409:'Otro dispositivo ha guardado cambios; se volverán a combinar.',422:'GitHub no ha aceptado el guardado. Revisa la rama y sus restricciones.'})[response.status]||'GitHub no ha completado la sincronización.';const error=new Error(message);error.status=response.status;throw error;}return response.json();}
 async verify(){const meta=await this.request('/repos/'+this.repository);if(meta.private!==true)throw new Error('La sincronización requiere un repositorio privado. No se enviaron tus datos.');if(meta.permissions?.push===false)throw new Error('El acceso permite leer, pero no guardar. Activa Contents: lectura y escritura.');if(!meta.default_branch)throw new Error('Inicializa el repositorio con un README antes de conectar.');this.branch=meta.default_branch;return {repository:meta.full_name||this.repository,branch:this.branch};}
 async read(){const result=await this.request('/repos/'+this.repository+'/contents/'+FILE+'?ref='+encodeURIComponent(this.branch),{missing:true});if(!result)return {document:emptyDocument(),sha:null};if(result.type!=='file'||result.size>MAX)throw new Error('El archivo de sesión no es válido o supera 5 MB. Exporta una copia y revisa el repositorio.');let content=result.content;if(result.encoding!=='base64')content=(await this.request('/repos/'+this.repository+'/git/blobs/'+result.sha)).content;const text=decodeUTF8(content);if(new TextEncoder().encode(text).length>MAX)throw new Error('La sesión supera 5 MB.');return {document:validateDocument(JSON.parse(text)),sha:result.sha};}
 async exchange(getDocument,onMerged){await this.verify();for(let attempt=0;attempt<3;attempt++){const remote=await this.read(),combined=mergeDocuments(remote.document,getDocument());onMerged(combined);const text=JSON.stringify(combined);if(new TextEncoder().encode(text).length>MAX)throw new Error('La sesión supera 5 MB. Exporta una copia antes de reducir tus registros.');if(JSON.stringify(remote.document)===text)return {changed:false};try{await this.request('/repos/'+this.repository+'/contents/'+FILE,{method:'PUT',body:{message:'Molab: sincronizar espacio personal',branch:this.branch,content:encodeUTF8(text),...(remote.sha?{sha:remote.sha}:{})}});return {changed:true};}catch(err){if(![409,422].includes(err.status)||attempt===2)throw err;}}}
}
