import {restrictionVendors} from './restriction-data.js?v=2.5.1';
export const restrictionVendor=id=>{const v=restrictionVendors.find(v=>v.id===id);if(!v)throw new Error('Fabricante no reconocido.');return v;};
export function numeric(value,label,allowZero=false){const raw=String(value??'').trim().replace(',','.');if(!raw||!/^[-+]?(?:\d+\.?\d*|\.\d+)(?:e[-+]?\d+)?$/i.test(raw))throw new Error(label+': introduce un número.');const n=Number(raw);if(!Number.isFinite(n)||(allowZero?n<0:n<=0))throw new Error(label+': debe ser '+(allowZero?'cero o positivo.':'positivo.'));return n;}
export function defaultDigest(vendor='neb'){const v=restrictionVendor(vendor);return {vendor,volume:v.volume,target:1000,material:'plasmid',mode:'batch',buffer:'auto',minutes:0,temperature:0,name:'Digestión de DNA',notes:'',excess:10,ackPartial:false,enzymes:[{id:v.enzymes[0].id,volume:v.enzymeVolume,stock:''},{id:'',volume:v.enzymeVolume,stock:''},{id:'',volume:v.enzymeVolume,stock:''}],samples:[{name:'Muestra 1',concentration:100},{name:'Muestra 2',concentration:''},{name:'Muestra 3',concentration:''}],importName:''};}
export function activityMinimum(activity){const value=String(activity??'').trim();if(!/^(?:<\d+|\d+(?:[–-]\d+)?)$/.test(value))return null;return value.startsWith('<')?0:Number(value.split(/[–-]/)[0]);}
export function recommendBuffer(vendor,ids){
 const v=restrictionVendor(vendor);if(!ids.length||ids.length>3||new Set(ids).size!==ids.length)throw new Error('Selecciona entre una y tres enzimas diferentes.');
 const enzymes=ids.map(id=>{const e=v.enzymes.find(e=>e.id===id);if(!e)throw new Error('Enzima sin compatibilidad revisada: '+id);return e;});
 const comparisons=v.buffers.map(b=>{
  const activities=enzymes.map(e=>({name:e.name,value:e.activities[b.id],star:(e.star||[]).includes(b.id),minimum:activityMinimum(e.activities[b.id])}));
  const known=activities.every(a=>a.minimum!==null);
  return {...b,activities,known,minimum:known?Math.min(...activities.map(a=>a.minimum)):null,mean:known?activities.reduce((n,a)=>n+a.minimum,0)/activities.length:null,star:activities.some(a=>a.star),notRecommended:activities.some(a=>a.value==='NR')};
 });
 const single=enzymes.length===1?enzymes[0].recommendedBuffer:null;
 const buffers=comparisons.filter(b=>b.known&&!b.notRecommended).sort((a,b)=>Number(b.id===single)-Number(a.id===single)||Number(a.star)-Number(b.star)||b.minimum-a.minimum||b.mean-a.mean||a.final-b.final||Number(b.id===v.preferred)-Number(a.id===v.preferred));
 if(!buffers.length)throw new Error('No hay datos de un buffer común recomendado para este conjunto.');
 return {best:buffers[0],buffers,comparisons,enzymes,temperatures:[...new Set(enzymes.map(e=>e.temp))]};
}
export function digestCalculation(c){
 const v=restrictionVendor(c.vendor),volume=numeric(c.volume,'Volumen final'),target=numeric(c.target,'Masa de DNA'),selected=c.enzymes.filter(e=>e.id),recommendation=recommendBuffer(c.vendor,selected.map(e=>e.id));
 const excess=numeric(c.excess??0,'Exceso',true),minutesInput=numeric(c.minutes??0,'Tiempo',true),temperatureInput=numeric(c.temperature??0,'Temperatura',true);if(excess>100)throw new Error('El exceso debe estar entre 0 y 100 %.');if(temperatureInput>100)throw new Error('La temperatura debe estar entre 0 y 100 °C.');if(!['batch','pool'].includes(c.mode))throw new Error('Formato de muestras no reconocido.');
 const buffer=c.buffer==='auto'?recommendation.best:recommendation.comparisons.find(b=>b.id===c.buffer);if(!buffer)throw new Error('Buffer no reconocido para este proveedor.');
 const enzymes=selected.map(e=>({...recommendation.enzymes.find(x=>x.id===e.id),volume:numeric(e.volume,'Volumen de '+e.id),stock:e.stock===''||e.stock==null?null:numeric(e.stock,'Stock de '+e.id)}));
 const enzymeVolume=enzymes.reduce((s,e)=>s+e.volume,0),bufferVolume=volume*buffer.final/buffer.stock,bsaVolume=v.bsa?volume/100:0;
 const errors=[],warnings=[];if(enzymeVolume>volume/10+1e-9)errors.push('Las enzimas suman '+enzymeVolume+' µL: supera el 10 % del volumen final. Reduce enzimas o aumenta el volumen.');
 if(recommendation.temperatures.length>1)errors.push('Temperaturas diferentes ('+recommendation.temperatures.join(' / ')+' °C). Este conjunto requiere un diseño secuencial; no iniciar como digestión simultánea.');
 if(buffer.star)errors.push('La fuente marca actividad star en este buffer. Selecciona otro buffer o productos HF.');
 if(buffer.notRecommended)errors.push('NR: el fabricante desaconseja este buffer para una o más enzimas por alta actividad star.');
 if(!buffer.known)errors.push('No hay datos publicados de actividad para todas las enzimas en el buffer elegido.');
 else if(buffer.minimum<50)errors.push('No hay actividad suficiente documentada para todas las enzimas en este buffer. Se requiere digestión secuencial o cambiar enzimas.');
 else if(buffer.minimum<100){warnings.push('Actividad parcial: '+buffer.activities.map(a=>a.name+' '+a.value+' %').join('; ')+'. Confirmar tiempo y cantidad en el fabricante.');if(!c.ackPartial)errors.push('Confirma la actividad parcial antes de iniciar.');}
 const samples=c.samples.filter(s=>String(s.name??'').trim()||String(s.concentration??'').trim()).filter(s=>!(String(s.concentration??'').trim()===''&&/^Muestra [123]$/.test(s.name||'')&&!c.importName));
 if(!samples.length)errors.push('Introduce al menos una muestra.');if(samples.length>10000)throw new Error('Máximo 10.000 muestras por cálculo.');
 const names=new Set();const massPerSample=c.mode==='pool'?target/samples.length:target;
 const rows=samples.map((s,i)=>{const name=String(s.name||'').trim();let concentration=null,dna=null,water=null,error='';try{if(!name)throw new Error('Falta identificador de muestra en la fila '+(i+1));if(names.has(name.toLowerCase()))throw new Error('Identificador duplicado: '+name);names.add(name.toLowerCase());concentration=numeric(s.concentration,'Concentración de '+name);dna=massPerSample/concentration;if(c.mode!=='pool'){water=volume-bufferVolume-bsaVolume-enzymeVolume-dna;if(water< -1e-9)throw new Error('Agua negativa: concentra el DNA o aumenta el volumen final.');water=Math.max(0,water);}if(dna>0&&dna<.2)warnings.push(name+': alícuota de DNA inferior a 0,2 µL; considera diluir el stock.');}catch(err){error=err.message;errors.push(error);}return {name,concentration,mass:massPerSample,dna,water,error,input:{...s}};});
 const poolDna=c.mode==='pool'&&rows.every(r=>!r.error)?rows.reduce((s,r)=>s+r.dna,0):null,poolWater=poolDna===null?null:volume-bufferVolume-bsaVolume-enzymeVolume-poolDna;if(poolWater!==null&&poolWater<0)errors.push('El pool necesita más volumen de DNA que el espacio disponible.');
 const material=['plasmid','pcr','genomic'].includes(c.material)?c.material:'plasmid';const recommendedMinutes=Math.max(...enzymes.map(e=>e.minutes[material]))+(v.id==='thermo'&&volume>20?5:0);const minutes=minutesInput||recommendedMinutes;const temperature=temperatureInput||recommendation.temperatures[0];
 if(temperature!==recommendation.temperatures[0])warnings.push('Temperatura modificada por el usuario: '+temperature+' °C; la compatibilidad indicada corresponde a la temperatura del fabricante.');
 if(v.id==='thermo'){const basis=material==='pcr'?200:1000,requiredDose=target/basis;if(enzymes.some(e=>e.volume<Math.max(1,requiredDose)))warnings.push('FastDigest: la dosis elegida es inferior a la escala de referencia (1 µL por '+basis+' ng de este sustrato). Revisa y ajusta la dosis en la ficha de cada producto; el tiempo mostrado no garantiza digestión a esa escala.');if(material!=='plasmid')warnings.push('Los tiempos corresponden al sustrato seleccionado, pero la configuración general procede de la receta de plasmidio. Verifica volumen final y dosis para PCR o DNA genómico en el manual.');}
 if(v.id==='thermo-conventional'){warnings.push('DNA purificado: ajustar dosis y duración a la ficha del producto y al sustrato. La matriz describe actividad relativa, no garantiza corte completo.');if(material==='pcr')warnings.push('Esta receta corresponde a PCR purificada. Para mezcla de PCR sin purificar usa la receta específica del manual: las sales residuales cambian las condiciones.');}
 return {vendor:v,volume,target,buffer,bufferVolume,bsaVolume,enzymes,rows,poolDna,poolWater,mode:c.mode||'batch',minutes,temperature,recommendedMinutes,recommendation,errors:[...new Set(errors)],warnings:[...new Set(warnings)],valid:!errors.length};
}
export function importedSamples(matrix,{header=0,nameColumn=0,concentrationColumn=1,unit='ng/µL'}={}){
 if(nameColumn===concentrationColumn)throw new Error('Selecciona columnas diferentes.');const factor={'ng/µL':1,'ng/mL':.001,'µg/µL':1000,'µg/mL':1}[unit];if(!factor)throw new Error('Unidad no compatible.');
 const rows=matrix.slice(header+1).map((r,i)=>({name:String(r[nameColumn]??'').trim(),rawConcentration:r[concentrationColumn]??'',sourceRow:header+i+2})).filter(s=>s.name||String(s.rawConcentration).trim());if(!rows.length)throw new Error('No hay filas de muestras debajo de la cabecera.');if(rows.length>10000)throw new Error('Máximo 10.000 muestras.');
 return rows.map(s=>{let concentration=s.rawConcentration;try{concentration=numeric(concentration,'Fila '+s.sourceRow)*factor;}catch{/* Keep the failed measurement visible for correction. */}return {...s,concentration,sourceUnit:unit};});
}
export function digestText(c,r){const f=n=>n==null?'—':Number(n.toFixed(4)).toString();const headers=['Muestra','Stock ng/µL','DNA ng','DNA µL','Agua µL','Buffer µL',...r.enzymes.map(e=>e.name+' µL'),...(r.bsaVolume?['BSA µL']:[]),'Estado'];const rows=r.rows.map(s=>[s.name,f(s.concentration),f(s.mass),f(s.dna),r.mode==='pool'?'En pool':f(s.water),r.mode==='pool'?'En pool':f(r.bufferVolume),...r.enzymes.map(e=>r.mode==='pool'?'En pool':f(e.volume)),...(r.bsaVolume?[r.mode==='pool'?'En pool':f(r.bsaVolume)]:[]),s.error||'Calculado']);
 return ['# '+c.name,'Molab 2.5.1 · '+new Date().toISOString(),'Fabricante: '+r.vendor.name,'Modo: '+(r.mode==='pool'?'Pool físico; masa total repartida por igual':'Una reacción independiente por muestra'),'Volumen final: '+r.volume+' µL · DNA objetivo: '+r.target+' ng','Buffer: '+r.buffer.name+' '+r.buffer.final+'X · '+r.buffer.color,'Incubación: '+r.temperature+' °C · '+r.minutes+' min','',headers.join(' | '),headers.map(()=>'---').join(' | '),...rows.map(x=>x.map(v=>String(v).replace(/[|\r\n]/g,' ')).join(' | ')),...(r.mode==='pool'?['',`Pool: DNA ${f(r.poolDna)} µL; agua ${f(r.poolWater)} µL; buffer ${f(r.bufferVolume)} µL; ${r.enzymes.map(e=>e.name+' '+f(e.volume)+' µL').join('; ')}${r.bsaVolume?'; BSA '+f(r.bsaVolume)+' µL':''}`]:[]),'',...r.errors,...r.warnings,'Notas: '+(c.notes||''),'Actividad en el buffer elegido: '+r.enzymes.map(e=>e.name+' '+(e.activities[r.buffer.id]===undefined?'Sin datos':e.activities[r.buffer.id]==='NR'?'NR (no recomendado)':e.activities[r.buffer.id]+' %')+((e.star||[]).includes(r.buffer.id)?' · actividad star':'')).join('; '),...r.enzymes.map(e=>{const b=r.vendor.buffers.find(b=>b.id===e.recommendedBuffer);return e.name+': '+(b?'buffer individual '+b.name+' '+b.final+'X · '+b.color+'; ':'')+'fuente '+(e.manual||e.product||e.source);}), 'Fuente: '+r.vendor.source,'Compatibilidad: '+r.vendor.compatibility].join('\n');
}
